#ifndef	BUTTONS_SPR_MANAGEMENT_HEADER
#define BUTTONS_SPR_MANAGEMENT_HEADER

#define	BUTTONS_STATUS_NORMAL				0				//보통 상태에서의 버튼
#define	BUTTONS_STATUS_PRESSED				1				//버튼이 이 눌려졌을때.
#define	BUTTONS_STATUS_ONMOUSE				2				//마우스가 버튼 위에 있을때.

#define	BUTTONS_1_NORMAL					0

#define	TOTAL_BUTTONS_KINDOF_NUM			10				//총 버튼은 TOTAL_BUTTONS_KINDOF_NUM종류가 있다.
#define	BUTTONS_TYPE_01_01					0				
#define	BUTTONS_TYPE_02_01					1				
#define	BUTTONS_TYPE_03_01					2				
#define	BUTTONS_TYPE_04_01					3
#define	BUTTONS_TYPE_05_01					4
#define	BUTTONS_TYPE_06_01					5
#define	BUTTONS_TYPE_07_01					6
#define	BUTTONS_TYPE_08_01					7				
#define	BUTTONS_TYPE_09_01					8				
#define	BUTTONS_TYPE_10_01					9				

#define	GET_BUTTON_INDEX_TYPE_01(X, Y)		(((X) * 3) + (Y))


#define	BUTTONS_FILENAME_TYPE_01_01			"yfnt\\buttons101.spr"
#define	BUTTONS_FILENAME_TYPE_02_01			"yfnt\\buttons201.spr"
#define	BUTTONS_FILENAME_TYPE_03_01			"yfnt\\buttons301.spr"
#define	BUTTONS_FILENAME_TYPE_04_01			""
#define	BUTTONS_FILENAME_TYPE_05_01			""
#define	BUTTONS_FILENAME_TYPE_06_01			"yfnt\\buttons601.spr"
#define	BUTTONS_FILENAME_TYPE_07_01			"yfnt\\buttons701.spr"
#define	BUTTONS_FILENAME_TYPE_08_01			"yfnt\\buttons801.spr"
#define	BUTTONS_FILENAME_TYPE_09_01			"yfnt\\buttons901.spr"
#define	BUTTONS_FILENAME_TYPE_10_01			"yfnt\\buttons1001.spr"

#define	BUTTONS_INSAVELOAD_BUTTONS			BUTTONS_TYPE_01_01	
#define	BUTTONS_INFO_BUTTONS				BUTTONS_TYPE_01_01
#define	BUTTONS_GAMEMENU_BUTTONS			BUTTONS_TYPE_02_01
#define	BUTTONS_BATTLENET_BUTTONS			BUTTONS_TYPE_03_01
#define	BUTTONS_CHOOSEPLAYER_2_BUTTONS		BUTTONS_TYPE_02_01
#define	BUTTONS_GETNAME_BUTTONS				BUTTONS_TYPE_06_01
#define	BUTTONS_MAINMENU_1_BUTTONS			BUTTONS_TYPE_06_01
#define	BUTTONS_CHOOSEPLAYER_1_BUTTONS		BUTTONS_TYPE_06_01
#define	BUTTONS_RESULT_BUTTONS				BUTTONS_TYPE_07_01
#define BUTTONS_INOPTION_BUTTONS			BUTTONS_TYPE_07_01
#define	BUTTONS_OBJECTIVE_BUTTONS			BUTTONS_TYPE_07_01
#define	BUTTONS_SERVICEPROVIDER_2_BUTTONS	BUTTONS_TYPE_07_01	
#define	BUTTONS_INOPTION_LARGE_B			BUTTONS_TYPE_08_01	
#define	BUTTONS_INOPTION_SMALL_B			BUTTONS_TYPE_09_01	
#define	BUTTONS_INOPTION_SCROLL_B			BUTTONS_TYPE_10_01	

//BUTTONS_GLOBAL_BUTTONS에 대한 사항.
#define	BUTTON_FONTNUM_GLOBAL_DECIDE					0
#define	BUTTON_FONTNUM_GLOBAL_BACK						1
#define	BUTTON_FONTNUM_GLOBAL_EXIT						2
#define	BUTTON_FONTNUM_GLOBAL_SEARCH					3
#define	BUTTON_FONTNUM_GLOBAL_CREATE					4
#define	BUTTON_FONTNUM_GLOBAL_JOIN						5
#define	BUTTON_FONTNUM_GLOBAL_REPLAY					6
#define	BUTTON_FONTNUM_GLOBAL_GOPLAY					7

//BUTTONS_CHOOSENATION_BUTONS에 대한 사항.
#define	BUTTONS_FONTNUM_CHOOSENATION_BACK				1

//BUTTONS_GAMEMENU_BUTTONS에 대한 사항.
#define	BUTTON_FONTNUM_GAMEMENU_CONTINUE				0
#define	BUTTON_FONTNUM_GAMEMENU_OBJECTIVE				1
#define	BUTTON_FONTNUM_GAMEMENU_OPTION					2
#define	BUTTON_FONTNUM_GAMEMENU_MAINMENU				3
#define	BUTTON_FONTNUM_GAMEMENU_SAVE					4
#define	BUTTON_FONTNUM_GAMEMENU_LOAD					5
#define	BUTTON_FONTNUM_GAMEMENU_RESTART					6
#define	BUTTON_FONTNUM_GAMEMENU_EXIT					7

//BUTTONS_INSAVELOAD_BUTTONS에 대한 사항.
#define	BUTTON_FONTNUM_INSAVELOAD_LOAD					10
#define	BUTTON_FONTNUM_INSAVELOAD_SAVE					11
#define	BUTTON_FONTNUM_INSAVELOAD_CANCEL				1

//BUTTONS_INOPTION_BUTTONS에 대한 사항.
#define	BUTTON_FONTNUM_INOPTION_DECIDE					0
#define	BUTTON_FONTNUM_INOPTION_CANCEL					1

//BUTTONS_RESULT_BUTTONS에대한 사항
#define	BUTTON_FONTNUM_RESULT_DECIDE					2

//BUTTONS_OBJECTIVE_BUTTONS에 대한 사항.
#define	BUTTONS_FONTNUM_OBJECTIVE_DECIDE				0

//BUTTON_OKCANCEL_BUTTONS에 대한 사항.
#define	BUTTONS_FONTNUM_OKCANCEL_OK						0
#define	BUTTONS_FONTNUM_OKCANCEL_CANCEL					1

//BUTTONS_GETNAME_BUTTONS에 대한 사항.
#define	BUTTONS_FONTNUM_GETNAME_OK						4
#define	BUTTONS_FONTNUM_GETNAME_CANCEL					5

// BUTTONS_SETGAME_BUTTONS에 대한 사항.
#define	BUTTONS_FONTNUM_SETGAME_OK						0
#define	BUTTONS_FONTNUM_SETGAME_CANCEL					1

//BUTTONS_INFO_BUTTONS에 대한 사항.
#define	BUTTONS_FONTNUM_INFO_OK							0

//BUTTONS_CHOOSEPLAYER_1_BUTTONS에 대한 사항.
#define	BUTTONS_FONTNUM_CHOOSEPLAYER_1_OK				4

//BUTTONS_CHOOSEPLAYER_2_BUTTONS에 대한 사항.
#define	BUTTONS_FONTNUM_CHOOSEPLAYER_2_ADD				10
#define	BUTTONS_FONTNUM_CHOOSEPLAYER_2_RENAME			8
#define	BUTTONS_FONTNUM_CHOOSEPLAYER_2_DELETE			9

//BUTTONS_SELECTSTAGE_BUTTONS에 대한 사항.
#define	BUTTONS_FONTNUM_SELECTSTAGE_OK					0
#define	BUTTONS_FONTNUM_SELECTSTAGE_CANCEL				1

// BUTTONS_SELECTSITE_BUTTONS에 대한 사항.
#define BUTTONS_FONTNUM_SELECTSITE_HQTEAM				0
#define	BUTTONS_FONTNUM_SELECTSITE_THEGAME				1
#define	BUTTONS_FONTNUM_SELECTSITE_HQNET				2



	// BUTTONS_BATTLENET_BUTTONS에 대한 사항.
#define	BUTTONS_FONTNUM_BATTLENET_OK				0
#define	BUTTONS_FONTNUM_BATTLENET_CANCEL			0	



#endif


