#include <GSL.h>
#include <main.h>
#include <clGame.h>
#include <etc.h>

#include "music.h"
#include <SoundManager.h>
#include "message.h"
//#include <OnlineWorld.h>
#include <map.h>
#include "charanimation.h"
#include <KindInfo.h>
#include "bindjxfile.h"
#include "OnlineCommonParser.h"		// sagolboss (2004/08/11 16:40) : 공용 파서기 추가

extern _clGame				*pGame;
extern	clock_t				CurrentClock;		// 시간 관련 
extern	_Map 				Map;
extern	SoundManager		*g_pSoundManager;
extern	SHORT				GameStatus;			// 현재의 게임 상황을 알리는 변수 
extern char					SavePath[];			// 현재 게임이 설치된 경로 
extern	_KindInfo			KI[];				// 캐릭터 종류별 데이터 

void _EffectData::Free()
{
	// 모든 효과음을 다 해제한다. 
	for(SHORT i=0;i<EffectNumber;i++)
	{
		EffectID[i]=0;
	}
}

BOOL _EffectData::Play(SI32 x, SI32 y)	
{
	SHORT	index;
	SI32	i;
	BOOL	bPlay;
	SI32	listenerX, listenerY;

	if( g_pSoundManager == NULL )	return FALSE;

	// 준비된 효과음이 있다면, 
	if( EffectNumber == 0 )
	{
		clGrp.Error("No Sound", "No Sound");
		return TRUE;
	}

	/** EffectSound.txt 파일을 보면 공통된 Enum 값을 가진 값들이 있다. 
		해당 되는 Enum에 대한 사운드 파일을 플레이 할때 Enum 값들중에 공통된 것들이 있으면
		이 공통된것들 중에 하나만을 랜덤으로 플레이 하게 된다.
		EffectNumber는 해당되는 Enum 값에 대한 공통으로 있는 Enum들의 갯수이다.
	*/
	index = CurrentClock % EffectNumber;

	if( GameStatus == GS_GAME )
	{
		listenerX = Map.VirtualMapX,	listenerY = Map.VirtualMapY;
		// (x, y) 가 (0, 0)일 때는 3D사운드가 아니다.
		if( x < 0 || x >= Map.MH.MapXsize)			x = 0;
		if( y < 0 || y >= Map.MH.MapYsize)			y = 0;
	}
	else
	{
		listenerX = 0,	listenerY = 0;
	}

	if( x==0 && y==0 )	x = listenerX, y = listenerY;


	g_pSoundManager->SetCharPosition_Quarter(EffectID[index], x, y);	

	bPlay = TRUE;
	// Stop 속성이 0인 경우, 이 ID에 해당하는 효과음 중 하나라도 플레이 중이라면 플레이하지 않는다.
	if( g_pSoundManager->IsStop(EffectID[index]) == FALSE )
	{
		for( i=0; i<EffectNumber; i++ )
		{
			if( g_pSoundManager->IsPlaying(EffectID[i]) == TRUE )
			{
				bPlay = FALSE;
				break;
			}
		}
	}
	if( bPlay )
	{
		g_pSoundManager->SetListenerPosition_Quarter(listenerX, listenerY);	

		g_pSoundManager->PlaySound(EffectID[index]);
	}

	return TRUE;
}

//-----------------------------------------------------------------------------
// Name: EffectDataMgr
// Code: damduk
// Desc: SoundEffect 데이터를 관리하는 클래스다.
//-----------------------------------------------------------------------------

EffectDataMgr::EffectDataMgr()
{
	// 사운드 데이터 초기화
	m_EffectBufferIndex = 0;
	memset(m_EffectData, 0, (sizeof(_EffectData) * MAX_EFFECT_TYPE));
	memset(m_EffectBuffer, 0, (sizeof(_EffectBuffer) * MAX_EFFECT_BUFFER));

#ifdef _USE_HASHCODE_EFFECTSOUND
	m_pMyHashTable = new CMyHashTable<int>(1500);
#endif
	
#ifndef _USE_HASHCODE_EFFECTSOUND
	SetProtocol();
#endif
	Init();
}

EffectDataMgr::~EffectDataMgr()
{
#ifdef _USE_HASHCODE_EFFECTSOUND //(2004-08-16 14:14 sagolboss)
	if( m_pMyHashTable)
	{
		delete m_pMyHashTable;
		m_pMyHashTable = NULL;
	}
#endif

	Free();
}

void EffectDataMgr::Init()
{
#ifndef _USE_HASHCODE_EFFECTSOUND
/** 수정자 : 김성준
    수정일 : 2004-08-11 오후 4:17
	설  명 : 기존에 있는 파서를 사용하지 않고 CommonParser를 사용한다 
*/
	FILE	*fp;
	CHAR	buffer[1024];
	SI32    siEffectNumber;
	char    szPrevName[128], szCurName[128];
	OnlineCommonParser	ocp;

	if((fp = BindJXFile::GetInstance()->GetFile( "EffectSound.txt" )) == NULL)
	{
		clGrp.Error("File Open Error", buffer);
		return ;
	}

	char	pszErrName[MAX_PATH];
	sprintf( pszErrName, "c:\\ParseErr_%s.txt", "EffectSound.txt" );
	ocp.SetErrFileName( pszErrName );

	/// 파싱을 시작한다.
	/// 파싱을 할때 return 되는 값들
	int		iRet, iErrLine;
	BOOL	bLess;

	if( ( iRet = ocp.Initialize( fp, iErrLine, bLess ) ) <= 0 )
	{
		ocp.PrintError( "OnlineText Error : Cannot Init! [ %s | Ret-%d | Line-%d | Less-%d ]", "EffectSound.txt", iRet, iErrLine, bLess );
		fclose( fp );
		return ;
	}

	while(1)
	{
		if( ocp.ParseDataLine() == 0 )	
			break;	

		/// 파싱을 할때 return 되는 값들
		int	 iLineNo, iColNo;
		ocp.GetValue(szCurName, 128, iLineNo, iColNo);
		ocp.GetValue(siEffectNumber, iLineNo, iColNo);
		
		// 효과음 종류가 바뀌면
		if(strcmp(szCurName, szPrevName) != 0)
			strcpy(szPrevName, szCurName);
	
		// 리스트에 넣는다.
		ENUM_EFFECT_TYPE EnumType = GetEnumType(szCurName);
		if(EnumType == EFFECT_INVALID)
		{
			clGrp.Error("Effect Parser Error", "%s", szCurName);
			continue;
		}

		m_EffectData[EnumType].EffectID[m_EffectData[EnumType].EffectNumber] = siEffectNumber;

		if(m_EffectData[EnumType].EffectNumber>= 5)
			clGrp.Error("Exceed Effect Number", "%s", szCurName);
		else
			m_EffectData[EnumType].EffectNumber++;	

		// 확인 사살 - 이것이 지금 마지막 라인째를 처리하고 있다면 브레이크
		if( ocp.IsEndOfLine() )	
			break;
	}
#endif

#ifdef _USE_HASHCODE_EFFECTSOUND
	FILE	*fp;
	CHAR	buffer[1024];
	char    szPrevName[128], szCurName[128];
	OnlineCommonParser	ocp;
	int     nHashCodeIndex = 1;

	if((fp = BindJXFile::GetInstance()->GetFile( "EffectSound.txt" )) == NULL)
	{
		clGrp.Error("File Open Error", buffer);
		return ;
	}

	/// 파싱을 시작한다.
	/// 파싱을 할때 return 되는 값들
	int		iRet, iErrLine;
	BOOL	bLess;

	if( ( iRet = ocp.Initialize( fp, iErrLine, bLess ) ) <= 0 )
	{
		ocp.PrintError( "OnlineText Error : Cannot Init! [ %s | Ret-%d | Line-%d | Less-%d ]", "EffectSound.txt", iRet, iErrLine, bLess );
		fclose( fp );
		return ;
	}

/* 이전에 있던 소스(04-08-23 소스)
	while(1)
	{
		if( ocp.ParseDataLine() == 0 )	
			break;	

		/// 파싱을 할때 return 되는 값들
		int	 iLineNo, iColNo;
		ocp.GetValue(szCurName, 128, iLineNo, iColNo);
		ocp.GetValue(siEffectNumber, iLineNo, iColNo);
		
		// 만약 빈칸(스페이스)가 들어있다면 고쳐주고 디버그 모드라면 에러를 띄운다
		if( !ClearBlankString(szCurName, szCurName))
		{
#ifdef _DEBUG
			clGrp.Error("EffectSound.txt Warning", "Blank String : %s", szCurName);
#endif
		}

		// 효과음 종류가 바뀌면
		if(strcmp(szCurName, szPrevName) != 0)
			strcpy(szPrevName, szCurName);

		if( GetMyHashTable()->Insert(szCurName, nHashCodeIndex))
			nHashCodeIndex++;

		// 리스트에 넣는다.
		int EnumType = GetEnumType(szCurName);
		if(EnumType == 0)
		{
			clGrp.Error("Effect Parser Error", "%s", szCurName);
			continue;
		}
		/** EffectSound.txt 파일을 보면 공통된 Enum 값을 가진 값들이 있다. 
			해당 되는 Enum에 대한 사운드 파일을 플레이 할때 Enum 값들중에 공통된 것들이 있으면
			이 공통된것들 중에 하나만을 랜덤으로 플레이 하게 된다.
			EffectNumber는 해당되는 Enum 값에 대한 공통으로 있는 Enum들의 갯수이다.
		*/
/*

		m_EffectData[EnumType].EffectID[m_EffectData[EnumType].EffectNumber] = siEffectNumber;

		if(m_EffectData[EnumType].EffectNumber>= 5)
			clGrp.Error("Exceed Effect Number", "%s", szCurName);
		else
			m_EffectData[EnumType].EffectNumber++;	


		// 확인 사살 - 이것이 지금 마지막 라인째를 처리하고 있다면 브레이크
		if( ocp.IsEndOfLine() )	
			break;
	}
*/

	int nParseLineCount    = 1;
	int nDummyEffectNumber = 0;

	while(1)
	{
		if( ocp.ParseDataLine() == 0 )	
			break;	

		/// 파싱을 할때 return 되는 값들
		int	 iLineNo, iColNo;
		ocp.GetValue(szCurName, 128, iLineNo, iColNo);
		
		// 만약 빈칸(스페이스)가 들어있다면 고쳐주고 디버그 모드라면 에러를 띄운다
		if( !ClearBlankString(szCurName, szCurName))
		{
#ifdef _DEBUG
			clGrp.Error("EffectSound.txt Warning", "Blank String : %s", szCurName);
#endif
		}

		// 효과음 종류가 바뀌면
		if(strcmp(szCurName, szPrevName) != 0)
			strcpy(szPrevName, szCurName);

		if( GetMyHashTable()->Insert(szCurName, nHashCodeIndex))
			nHashCodeIndex++;

		// 리스트에 넣는다.
		int EnumType = GetEnumType(szCurName);
		if(EnumType == 0)
		{
			clGrp.Error("Effect Parser Error", "%s", szCurName);
			continue;
		}
		/** EffectSound.txt 파일을 보면 공통된 Enum 값을 가진 값들이 있다. 
			해당 되는 Enum에 대한 사운드 파일을 플레이 할때 Enum 값들중에 공통된 것들이 있으면
			이 공통된것들 중에 하나만을 랜덤으로 플레이 하게 된다.
			EffectNumber는 해당되는 Enum 값에 대한 공통으로 있는 Enum들의 갯수이다.
		*/

		m_EffectData[EnumType].EffectID[m_EffectData[EnumType].EffectNumber] = nParseLineCount;

		if(m_EffectData[EnumType].EffectNumber>= 5)
			clGrp.Error("Exceed Effect Number", "%s", szCurName);
		else
			m_EffectData[EnumType].EffectNumber++;	


		// 확인 사살 - 이것이 지금 마지막 라인째를 처리하고 있다면 브레이크
		if( ocp.IsEndOfLine() )	
			break;

		nParseLineCount++;
	}

	ocp.Release();
	fclose( fp );
	fp = NULL;
#endif
}

void EffectDataMgr::Free()
{
	for(SHORT i=0; i < MAX_EFFECT_TYPE; i++)
		m_EffectData[i].Free();
}

#ifndef _USE_HASHCODE_EFFECTSOUND
BOOL PushEffect(SHORT effect, SHORT x, SHORT y)
{
	if(!pGame)	return FALSE;

	if(pGame->m_pEffectDataMgr->m_EffectBufferIndex >= MAX_EFFECT_BUFFER )		return FALSE;

	pGame->m_pEffectDataMgr->m_EffectBuffer[pGame->m_pEffectDataMgr->m_EffectBufferIndex++].Set(effect, x, y);
	return TRUE;
}
#else
BOOL HashCodePushEffect(const char* pszEffectName, SHORT x, SHORT y)
{
	if(!pGame)	return FALSE;
	
	if(pGame->m_pEffectDataMgr->m_EffectBufferIndex >= MAX_EFFECT_BUFFER )		return FALSE;

	int nEffectIndex = GetEffectDataMgr()->GetMyHashTable()->Find(pszEffectName);
	pGame->m_pEffectDataMgr->m_EffectBuffer[pGame->m_pEffectDataMgr->m_EffectBufferIndex++].Set(nEffectIndex, x, y);
	return TRUE;
}

BOOL HashCodePushEffect(int nEffectIndex, SHORT x, SHORT y)
{
	if(!pGame)	return FALSE;
	
	if(pGame->m_pEffectDataMgr->m_EffectBufferIndex >= MAX_EFFECT_BUFFER )		return FALSE;
	pGame->m_pEffectDataMgr->m_EffectBuffer[pGame->m_pEffectDataMgr->m_EffectBufferIndex++].Set(nEffectIndex, x, y);
	return TRUE;
}
#endif

// 버퍼에 저장된 소리를 하나 꺼내서 연주한다. 
void EffectDataMgr::Pop()
{
	if( m_EffectBufferIndex <= 0 )	
		return;
	
	// 버퍼에 저장된 것을 꺼낸다. 
	SHORT effect = m_EffectBuffer[0].Effect;
	SHORT x = m_EffectBuffer[0].X;
	SHORT y = m_EffectBuffer[0].Y;

	for(SHORT i=1; i<m_EffectBufferIndex; i++ )
	{
		m_EffectBuffer[i-1] = m_EffectBuffer[i];
	}
	m_EffectBufferIndex--;

	if( GameStatus == GS_GAME )
	{
		// 화면 중심과 주어진 좌표와의 상대적 거리를 구한다. 
		int sx=(x-Map.VirtualMapX);
		int sy=(y-Map.VirtualMapY);

		// 위치가 주어진 소리인데 거리가 멀면 소리내지 않는다. 
		if( x && y && (abs(sx)>17 || abs(sy)>17) )	return;
	}
	
	m_EffectData[effect].Play(x, y);
}


// kind에 의한 선택시 효과음 연주. 
void EffectDataMgr::PushEffectByKindWhenSelected(SI32 kind)
{
	SI32 kind2 = TransKindOnlineToImjin(kind);

	if(KI[kind2].m_siSelectEffect)
#ifndef _USE_HASHCODE_EFFECTSOUND
		PushEffect(KI[kind2].m_siSelectEffect, 0, 0);
#else
	    HashCodePushEffect(KI[kind2].m_siSelectEffect, 0, 0);
#endif
}

#ifndef _USE_HASHCODE_EFFECTSOUND
void EffectDataMgr::SetEnumType( int index, char *pszStr )	
{ 
	if( !pszStr || index <= EFFECT_FIRST || index >= MAX_EFFECT_TYPE ) return;
	strcpy( m_EffectData[index].m_pszString, pszStr ); 
}
ENUM_EFFECT_TYPE EffectDataMgr::GetEnumType( char *pszStr )
{
	if( !pszStr )		return EFFECT_INVALID;
	for( register int i=EFFECT_FIRST; i<MAX_EFFECT_TYPE; i++ )	
	{
		if( strcmp( m_EffectData[i].m_pszString, pszStr ) == 0 ) return (ENUM_EFFECT_TYPE)i;
	}
	return EFFECT_INVALID;
}
#else
int EffectDataMgr::GetEnumType( char *pszStr )
{
	return GetMyHashTable()->Find(pszStr);
}
#endif

const char* EffectDataMgr::GetEnumType( int enIndex )
{
	if( enIndex <= EFFECT_FIRST || enIndex >= MAX_EFFECT_TYPE )		return NULL;
	return (const char*)(m_EffectData[enIndex].m_pszString);
}

BOOL EffectDataMgr::ClearBlankString(char const* pszCheckString, char* pszOutCleanBlankString)
{
	string szCheckName = pszCheckString;
	int nBlankStringIndex = szCheckName.find(" ");

	if( nBlankStringIndex > 0)
	{
		szCheckName.erase( nBlankStringIndex, szCheckName.size());
		strcpy(pszOutCleanBlankString, szCheckName.c_str());
		return FALSE;
	}
	return TRUE;
}

#ifndef _USE_HASHCODE_EFFECTSOUND
void EffectDataMgr::SetProtocol()
{
#define SET_PROTOCOL( index )	SetEnumType( index, #index );
		
// 수열이 추가될 경우 이 부분 맨 아래 (//EOF앞쪽)에 추가시킨다.
	
	SET_PROTOCOL(EFFECT_ARROW)					// 1
	SET_PROTOCOL(EFFECT_ARROWHIT)
	SET_PROTOCOL(EFFECT_SWORD)
	SET_PROTOCOL(EFFECT_BIGSWORD)
	SET_PROTOCOL(EFFECT_GUN)
	SET_PROTOCOL(EFFECT_SCREAM)
	SET_PROTOCOL(EFFECT_CANNON)
	SET_PROTOCOL(EFFECT_CANNONEXP)
	SET_PROTOCOL(EFFECT_HORSEDIE)
	SET_PROTOCOL(EFFECT_HEAL)					// 10

	SET_PROTOCOL(EFFECT_SAM)
	SET_PROTOCOL(EFFECT_TANK)
	SET_PROTOCOL(EFFECT_CLICK)
	SET_PROTOCOL(EFFECT_TITLEBUTTON)
	SET_PROTOCOL(EFFECT_BUDA)
	SET_PROTOCOL(EFFECT_THUNDER)
	SET_PROTOCOL(EFFECT_BULL)
	SET_PROTOCOL(EFFECT_FLAME)
	SET_PROTOCOL(EFFECT_BOMB)
	SET_PROTOCOL(EFFECT_FIRE)					// 20

	SET_PROTOCOL(EFFECT_ELECTRIC)
	SET_PROTOCOL(EFFECT_SINK)
	SET_PROTOCOL(EFFECT_SHIPCANNON)
	SET_PROTOCOL(EFFECT_SHIPCANNONDOUBLE)
	SET_PROTOCOL(EFFECT_FARMERJDIE)
	SET_PROTOCOL(EFFECT_AIRPLANEDIE)
	SET_PROTOCOL(EFFECT_CROP)
	SET_PROTOCOL(EFFECT_TREE)
	SET_PROTOCOL(EFFECT_SMALLCANNON)
	SET_PROTOCOL(EFFECT_HALFEXP)				// 30

	SET_PROTOCOL(EFFECT_FARMERJWORK)
	SET_PROTOCOL(EFFECT_EARTHQUAKE)
	SET_PROTOCOL(EFFECT_SAMC)
	SET_PROTOCOL(EFFECT_MESSAGE)
	SET_PROTOCOL(EFFECT_SHALLOW)
	SET_PROTOCOL(EFFECT_DECIDEBUILD)
	SET_PROTOCOL(EFFECT_GENERAL4KATTACK)
	SET_PROTOCOL(EFFECT_NINJAJ)
	SET_PROTOCOL(EFFECT_REPAIRBUILD)
	SET_PROTOCOL(EFFECT_RIDEIN)					// 40

	SET_PROTOCOL(EFFECT_RIDEOUT)
	SET_PROTOCOL(EFFECT_WARP)
	SET_PROTOCOL(EFFECT_CANNON2CFIRE)
	SET_PROTOCOL(EFFECT_ARROWEXP)
	SET_PROTOCOL(EFFECT_SELECTCOUNTRY)
	SET_PROTOCOL(EFFECT_TEAM0)
	SET_PROTOCOL(EFFECT_TEAM1)
	SET_PROTOCOL(EFFECT_TEAM2)
	SET_PROTOCOL(EFFECT_TEAM3)
	SET_PROTOCOL(EFFECT_TEAM4)					// 50

	SET_PROTOCOL(EFFECT_TEAM5)
	SET_PROTOCOL(EFFECT_TEAM6)
	SET_PROTOCOL(EFFECT_TEAM7)
	SET_PROTOCOL(EFFECT_TEAM8)
	SET_PROTOCOL(EFFECT_TEAM9)
	SET_PROTOCOL(EFFECT_FIRETANKKHIT)
	SET_PROTOCOL(EFFECT_CANNONJ)
	SET_PROTOCOL(EFFECT_NINJA2JATTACK)
	SET_PROTOCOL(EFFECT_NINJA2JHIT)
	SET_PROTOCOL(EFFECT_JUSTICEK)				// 60

	SET_PROTOCOL(EFFECT_SPEAR2)
	SET_PROTOCOL(EFFECT_SPECIALGUN)
	SET_PROTOCOL(EFFECT_ITEMON)
	SET_PROTOCOL(EFFECT_ITEMOFF)
	SET_PROTOCOL(EFFECT_EXTINGUISH)
	SET_PROTOCOL(EFFECT_GETITEM)
	SET_PROTOCOL(EFFECT_EXP)
	SET_PROTOCOL(EFFECT_CANNON2KFIRE)
	SET_PROTOCOL(EFFECT_BUILD)
	SET_PROTOCOL(EFFECT_GENERAL4KMAGIC)			// 70

	SET_PROTOCOL(EFFECT_MAP1)
	SET_PROTOCOL(EFFECT_MAP2)
	SET_PROTOCOL(EFFECT_NIGHT)
	SET_PROTOCOL(EFFECT_DAY)
	SET_PROTOCOL(EFFECT_LEVELUP)
	SET_PROTOCOL(EFFECT_RAIN)
	SET_PROTOCOL(EFFECT_SNOW)
	SET_PROTOCOL(EFFECT_DROP)
	SET_PROTOCOL(EFFECT_EVENT)
	SET_PROTOCOL(EFFECT_STARTGAME)				// 80

	SET_PROTOCOL(EFFECT_KIMBOMB)
	SET_PROTOCOL(EFFECT_AIRMAGIC)
	SET_PROTOCOL(EFFECT_TORNADO)
	SET_PROTOCOL(EFFECT_MAGIC8J)
	SET_PROTOCOL(EFFECT_MAGIC4C)
	SET_PROTOCOL(EFFECT_MAGIC4EXP)
	SET_PROTOCOL(EFFECT_MAGIC6C)
	SET_PROTOCOL(EFFECT_USEITEM)
	SET_PROTOCOL(EFFECT_CARTOBUILD)
	SET_PROTOCOL(EFFECT_CLUB)					// 90

	SET_PROTOCOL(EFFECT_MANAGERWARNING)
	SET_PROTOCOL(EFFECT_DROPSTONE)
	SET_PROTOCOL(EFFECT_DROPWATER)
	SET_PROTOCOL(EFFECT_SNOWWOMANMAGIC)
	SET_PROTOCOL(EFFECT_GOLDDRAGONFIRE)
	SET_PROTOCOL(EFFECT_SEAKINGFIRE)
	SET_PROTOCOL(EFFECT_HORSESWORDJATTACK)
	SET_PROTOCOL(EFFECT_BUILDDONE)
	SET_PROTOCOL(EFFECT_UPGRADEDONE)
	SET_PROTOCOL(EFFECT_CANNOTMAKETHERE)		// 100

	SET_PROTOCOL(EFFECT_SAVEDONE)
	SET_PROTOCOL(EFFECT_CAPTUREENEMYBUILDMESSAGE)
	SET_PROTOCOL(EFFECT_CAPTUREDBUILDMESSAGE)
	SET_PROTOCOL(EFFECT_LEVELUPMESSAGE)
	SET_PROTOCOL(EFFECT_LEVELDOWNMESSAGE)
	SET_PROTOCOL(EFFECT_STEALTECHMESSAGE)
	SET_PROTOCOL(EFFECT_STOLENTECHMESSAGE)
	SET_PROTOCOL(EFFECT_BEATTACKEDMESSAGE)
	SET_PROTOCOL(EFFECT_TRAINSPOTDONEMESSAGE)
	SET_PROTOCOL(EFFECT_MINEEXPLODEMESSAGE)		// 110

	SET_PROTOCOL(EFFECT_WAIT_KW)
	SET_PROTOCOL(EFFECT_MOVE_KW)
	SET_PROTOCOL(EFFECT_HUNGRY_KW0)
	SET_PROTOCOL(EFFECT_HUNGRY_KW1)
	SET_PROTOCOL(EFFECT_HUNGRY_KW2)
	SET_PROTOCOL(EFFECT_EAT_KW0)
	SET_PROTOCOL(EFFECT_EAT_KW1)
	SET_PROTOCOL(EFFECT_EAT_KW2)
	SET_PROTOCOL(EFFECT_SELECT_KW)
	SET_PROTOCOL(EFFECT_ATTACK_KW)				// 120
	
	SET_PROTOCOL(EFFECT_DIE_KW)
	SET_PROTOCOL(EFFECT_WAIT_JW)
	SET_PROTOCOL(EFFECT_MOVE_JW)
	SET_PROTOCOL(EFFECT_HUNGRY_JW0)
	SET_PROTOCOL(EFFECT_HUNGRY_JW1)
	SET_PROTOCOL(EFFECT_HUNGRY_JW2)
	SET_PROTOCOL(EFFECT_EAT_JW0)
	SET_PROTOCOL(EFFECT_EAT_JW1)
	SET_PROTOCOL(EFFECT_EAT_JW2)
	SET_PROTOCOL(EFFECT_SELECT_JW)				// 130

	SET_PROTOCOL(EFFECT_ATTACK_JW)
	SET_PROTOCOL(EFFECT_DIE_JW)
	SET_PROTOCOL(EFFECT_WAIT_KM)
	SET_PROTOCOL(EFFECT_MOVE_KM)
	SET_PROTOCOL(EFFECT_HUNGRY_KM0)
	SET_PROTOCOL(EFFECT_HUNGRY_KM1)
	SET_PROTOCOL(EFFECT_HUNGRY_KM2)
	SET_PROTOCOL(EFFECT_EAT_KM0)
	SET_PROTOCOL(EFFECT_EAT_KM1)
	SET_PROTOCOL(EFFECT_EAT_KM2)				// 140

	SET_PROTOCOL(EFFECT_SELECT_KM)
	SET_PROTOCOL(EFFECT_ATTACK_KM)
	SET_PROTOCOL(EFFECT_DIE_KM)
	SET_PROTOCOL(EFFECT_WAIT_JM)
	SET_PROTOCOL(EFFECT_MOVE_JM)
	SET_PROTOCOL(EFFECT_HUNGRY_JM0)
	SET_PROTOCOL(EFFECT_HUNGRY_JM1)
	SET_PROTOCOL(EFFECT_HUNGRY_JM2)
	SET_PROTOCOL(EFFECT_EAT_JM0)
	SET_PROTOCOL(EFFECT_EAT_JM1)				// 150

	SET_PROTOCOL(EFFECT_EAT_JM2)
	SET_PROTOCOL(EFFECT_SELECT_JM)
	SET_PROTOCOL(EFFECT_ATTACK_JM)
	SET_PROTOCOL(EFFECT_DIE_JM)
	SET_PROTOCOL(EFFECT_WAIT_TM)
	SET_PROTOCOL(EFFECT_MOVE_TM)
	SET_PROTOCOL(EFFECT_HUNGRY_TM0)
	SET_PROTOCOL(EFFECT_HUNGRY_TM1)
	SET_PROTOCOL(EFFECT_HUNGRY_TM2)
	SET_PROTOCOL(EFFECT_EAT_TM0)				// 160

	SET_PROTOCOL(EFFECT_EAT_TM1)
	SET_PROTOCOL(EFFECT_EAT_TM2)
	SET_PROTOCOL(EFFECT_SELECT_TM)
	SET_PROTOCOL(EFFECT_ATTACK_TM)
	SET_PROTOCOL(EFFECT_DIE_TM)
	SET_PROTOCOL(EFFECT_WAIT_TW)
	SET_PROTOCOL(EFFECT_MOVE_TW)
	SET_PROTOCOL(EFFECT_HUNGRY_TW0)
	SET_PROTOCOL(EFFECT_HUNGRY_TW1)
	SET_PROTOCOL(EFFECT_HUNGRY_TW2)				// 170

	SET_PROTOCOL(EFFECT_EAT_TW0)
	SET_PROTOCOL(EFFECT_EAT_TW1)
	SET_PROTOCOL(EFFECT_EAT_TW2)
	SET_PROTOCOL(EFFECT_SELECT_TW)
	SET_PROTOCOL(EFFECT_ATTACK_TW)
	SET_PROTOCOL(EFFECT_DIE_TW)
	SET_PROTOCOL(EFFECT_WAIT_CM)
	SET_PROTOCOL(EFFECT_MOVE_CM)
	SET_PROTOCOL(EFFECT_HUNGRY_CM0)
	SET_PROTOCOL(EFFECT_HUNGRY_CM1)				// 180

	SET_PROTOCOL(EFFECT_HUNGRY_CM2)
	SET_PROTOCOL(EFFECT_EAT_CM0)
	SET_PROTOCOL(EFFECT_EAT_CM1)
	SET_PROTOCOL(EFFECT_EAT_CM2)
	SET_PROTOCOL(EFFECT_SELECT_CM)
	SET_PROTOCOL(EFFECT_ATTACK_CM)
	SET_PROTOCOL(EFFECT_DIE_CM)
	SET_PROTOCOL(EFFECT_WAIT_CW)
	SET_PROTOCOL(EFFECT_MOVE_CW)
	SET_PROTOCOL(EFFECT_HUNGRY_CW0)				// 190

	SET_PROTOCOL(EFFECT_HUNGRY_CW1)
	SET_PROTOCOL(EFFECT_HUNGRY_CW2)
	SET_PROTOCOL(EFFECT_EAT_CW0)
	SET_PROTOCOL(EFFECT_EAT_CW1)
	SET_PROTOCOL(EFFECT_EAT_CW2)
	SET_PROTOCOL(EFFECT_SELECT_CW)
	SET_PROTOCOL(EFFECT_ATTACK_CW)
	SET_PROTOCOL(EFFECT_DIE_CW)
	SET_PROTOCOL(EFFECT_SELECT_FARMERK)
	SET_PROTOCOL(EFFECT_SELECT_FARMERC)			// 200

	SET_PROTOCOL(EFFECT_SELECT_SWORDC)
	SET_PROTOCOL(EFFECT_SELECT_BUDAC)
	SET_PROTOCOL(EFFECT_SELECT_GUNC)
	SET_PROTOCOL(EFFECT_SELECT_HEAVYGUNC)
	SET_PROTOCOL(EFFECT_SELECT_MECH)
	SET_PROTOCOL(EFFECT_SELECT_ATTACKERC)
	SET_PROTOCOL(EFFECT_SELECT_GENERALK1)
	SET_PROTOCOL(EFFECT_SELECT_GENERALK2)
	SET_PROTOCOL(EFFECT_SELECT_GENERALK3)
	SET_PROTOCOL(EFFECT_SELECT_GENERALK4)		// 210

	SET_PROTOCOL(EFFECT_SELECT_GENERALK5)
	SET_PROTOCOL(EFFECT_SELECT_GENERALK6)
	SET_PROTOCOL(EFFECT_SELECT_GENERALK7)
	SET_PROTOCOL(EFFECT_SELECT_GENERALK8)
	SET_PROTOCOL(EFFECT_SELECT_GENERALJ1)
	SET_PROTOCOL(EFFECT_SELECT_GENERALJ2)
	SET_PROTOCOL(EFFECT_SELECT_GENERALJ3)
	SET_PROTOCOL(EFFECT_SELECT_GENERALJ4)
	SET_PROTOCOL(EFFECT_SELECT_GENERALJ5)
	SET_PROTOCOL(EFFECT_SELECT_GENERALJ6)		// 220

	SET_PROTOCOL(EFFECT_SELECT_GENERALJ7)
	SET_PROTOCOL(EFFECT_SELECT_GENERALJ8)
	SET_PROTOCOL(EFFECT_SELECT_GENERAL_C1)
	SET_PROTOCOL(EFFECT_SELECT_GENERAL_C3)
	SET_PROTOCOL(EFFECT_SELECT_GENERAL_C4)
	SET_PROTOCOL(EFFECT_SELECT_GENERAL_C5)
	SET_PROTOCOL(EFFECT_DIE_FARMERK)
	SET_PROTOCOL(EFFECT_DIE_FARMERC)
	SET_PROTOCOL(EFFECT_DIE_SWORDC)
	SET_PROTOCOL(EFFECT_DIE_BUDAC)				// 230

	SET_PROTOCOL(EFFECT_DIE_GUNC)
	SET_PROTOCOL(EFFECT_DIE_HEAVYGUNC)
	SET_PROTOCOL(EFFECT_DIE_ATTACKERC)
	SET_PROTOCOL(EFFECT_DIE_EAGLEC)
	SET_PROTOCOL(EFFECT_MOVE_FARMERK)
	SET_PROTOCOL(EFFECT_MOVE_FARMERC)
	SET_PROTOCOL(EFFECT_MOVE_SWORDC)
	SET_PROTOCOL(EFFECT_MOVE_GUNC)
	SET_PROTOCOL(EFFECT_MOVE_HEAVYGUNC)
	SET_PROTOCOL(EFFECT_MOVE_BUDAC)				// 240

	SET_PROTOCOL(EFFECT_MOVE_GENERALK1)
	SET_PROTOCOL(EFFECT_MOVE_GENERALK2)
	SET_PROTOCOL(EFFECT_MOVE_GENERALK3)
	SET_PROTOCOL(EFFECT_MOVE_GENERALK4)
	SET_PROTOCOL(EFFECT_MOVE_GENERALK5)
	SET_PROTOCOL(EFFECT_MOVE_GENERALK6)
	SET_PROTOCOL(EFFECT_MOVE_GENERALK7)
	SET_PROTOCOL(EFFECT_MOVE_GENERALK8)
	SET_PROTOCOL(EFFECT_MOVE_GENERALJ1)
	SET_PROTOCOL(EFFECT_MOVE_GENERALJ2)			// 250

	SET_PROTOCOL(EFFECT_MOVE_GENERALJ3)
	SET_PROTOCOL(EFFECT_MOVE_GENERALJ4)
	SET_PROTOCOL(EFFECT_MOVE_GENERALJ5)
	SET_PROTOCOL(EFFECT_MOVE_GENERALJ6)
	SET_PROTOCOL(EFFECT_MOVE_GENERALJ7)
	SET_PROTOCOL(EFFECT_MOVE_GENERALJ8)
	SET_PROTOCOL(EFFECT_MOVE_GENERAL_C1)
	SET_PROTOCOL(EFFECT_MOVE_GENERAL_C3)
	SET_PROTOCOL(EFFECT_MOVE_GENERAL_C4)
	SET_PROTOCOL(EFFECT_MOVE_GENERAL_C5)		// 260

	SET_PROTOCOL(EFFECT_MOVE_SHIP)
	SET_PROTOCOL(EFFECT_MOVE_CANNON2K)
	SET_PROTOCOL(EFFECT_MOVE_EAGLEC)
	SET_PROTOCOL(EFFECT_MOVE_CANNONJ)
	SET_PROTOCOL(EFFECT_MOVE_ATTACKERJ)
	SET_PROTOCOL(EFFECT_ATTACK_FARMERK)
	SET_PROTOCOL(EFFECT_ATTACK_FARMERC)
	SET_PROTOCOL(EFFECT_ATTACK_SWORDC)
	SET_PROTOCOL(EFFECT_ATTACK_GUNC)
	SET_PROTOCOL(EFFECT_ATTACK_HEAVYGUNC)		// 270

	SET_PROTOCOL(EFFECT_ATTACK_BUDAC)
	SET_PROTOCOL(EFFECT_ATTACK_GENERALK1)
	SET_PROTOCOL(EFFECT_ATTACK_GENERALK2)
	SET_PROTOCOL(EFFECT_ATTACK_GENERALK3)
	SET_PROTOCOL(EFFECT_ATTACK_GENERALK4)
	SET_PROTOCOL(EFFECT_ATTACK_GENERALK5)
	SET_PROTOCOL(EFFECT_ATTACK_GENERALK6)
	SET_PROTOCOL(EFFECT_ATTACK_GENERALK7)
	SET_PROTOCOL(EFFECT_ATTACK_GENERALK8)
	SET_PROTOCOL(EFFECT_ATTACK_GENERALJ1)		// 280

	SET_PROTOCOL(EFFECT_ATTACK_GENERALJ2)
	SET_PROTOCOL(EFFECT_ATTACK_GENERALJ3)
	SET_PROTOCOL(EFFECT_ATTACK_GENERALJ4)
	SET_PROTOCOL(EFFECT_ATTACK_GENERALJ5)
	SET_PROTOCOL(EFFECT_ATTACK_GENERALJ6)
	SET_PROTOCOL(EFFECT_ATTACK_GENERALJ7)
	SET_PROTOCOL(EFFECT_ATTACK_GENERALJ8)
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_C1)
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_C3)
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_C4)		// 290

	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_C5)
	SET_PROTOCOL(EFFECT_ON_ATTACK_WEIRDPLANT)
	SET_PROTOCOL(EFFECT_ON_DIE_WEIRDPLANT)
	SET_PROTOCOL(EFFECT_ON_DIE_STARFISH)
	SET_PROTOCOL(EFFECT_ON_ITEMONOFF)
	SET_PROTOCOL(EFFECT_ON_DIE_TIGER)
	SET_PROTOCOL(EFFECT_ON_DIE_FURHEADDEMON)
	SET_PROTOCOL(EFFECT_ON_DIE_DEER)
	SET_PROTOCOL(EFFECT_ON_DIE_BAT)
	SET_PROTOCOL(EFFECT_ON_DIE_GACKDAGUI)		// 300

	SET_PROTOCOL(EFFECT_ON_DIE_GATPHA)
	SET_PROTOCOL(EFFECT_ON_DIE_DOGDEMON)
	SET_PROTOCOL(EFFECT_ON_DIE_DUEOKSINI)
	SET_PROTOCOL(EFFECT_ON_DIE_RACCOONDOG)
	SET_PROTOCOL(EFFECT_ON_DIE_HUNGRYDEMON)
	SET_PROTOCOL(EFFECT_ON_DIE_EATERDEMON)
	SET_PROTOCOL(EFFECT_ON_DIE_ONI)
	SET_PROTOCOL(EFFECT_ON_DIE_GOLDDRAGON)
	SET_PROTOCOL(EFFECT_ON_DIE_FIREDRAGON)
	SET_PROTOCOL(EFFECT_ON_DIE_SNOWDEMON)		// 310

	SET_PROTOCOL(EFFECT_ON_DIE_TOAD)
	SET_PROTOCOL(EFFECT_ON_DIE_CENTIPEDE)
	SET_PROTOCOL(EFFECT_ON_DIE_BANDIT1)
	SET_PROTOCOL(EFFECT_ON_DIE_BANDIT2)
	SET_PROTOCOL(EFFECT_ON_DIE_BANDIT3)
	SET_PROTOCOL(EFFECT_ON_DIE_BANDIT4)
	SET_PROTOCOL(EFFECT_ON_DIE_SWORDPIRATE)
	SET_PROTOCOL(EFFECT_SELECT_ONGHWA)
	SET_PROTOCOL(EFFECT_MOVE_ONGHWA)
	SET_PROTOCOL(EFFECT_ATTACK_ONGHWA)			// 320

	SET_PROTOCOL(EFFECT_DIE_ONGHWA)
	SET_PROTOCOL(EFFECT_SELECT_BANDIT1)
	SET_PROTOCOL(EFFECT_SELECT_PORTERK)
	SET_PROTOCOL(EFFECT_MOVE_PORTERK)
	SET_PROTOCOL(EFFECT_DIE_PORTERK)
	SET_PROTOCOL(EFFECT_SELECT_SWORDK)
	SET_PROTOCOL(EFFECT_MOVE_SWORDK)
	SET_PROTOCOL(EFFECT_ATTACK_SWORDK)
	SET_PROTOCOL(EFFECT_DIE_SWORDK)
	SET_PROTOCOL(EFFECT_SELECT_ARCHERK)			// 330

	SET_PROTOCOL(EFFECT_MOVE_ARCHERK)
	SET_PROTOCOL(EFFECT_ATTACK_ARCHERK)
	SET_PROTOCOL(EFFECT_DIE_ARCHERK)
	SET_PROTOCOL(EFFECT_SELECT_BUDAK)
	SET_PROTOCOL(EFFECT_MOVE_BUDAK)
	SET_PROTOCOL(EFFECT_ATTACK_BUDAK)
	SET_PROTOCOL(EFFECT_DIE_BUDAK)
	SET_PROTOCOL(EFFECT_SELECT_HORSEARCHERK)
	SET_PROTOCOL(EFFECT_MOVE_HORSEARCHERK)
	SET_PROTOCOL(EFFECT_ATTACK_HORSEARCHERK)	// 340

	SET_PROTOCOL(EFFECT_DIE_HORSEARCHERK)
	SET_PROTOCOL(EFFECT_SELECT_JUSTICEK)
	SET_PROTOCOL(EFFECT_MOVE_JUSTICEK)
	SET_PROTOCOL(EFFECT_ATTACK_JUSTICEK)
	SET_PROTOCOL(EFFECT_DIE_JUSTICEK)
	SET_PROTOCOL(EFFECT_SELECT_ADVBUDAJ)
	SET_PROTOCOL(EFFECT_MOVE_ADVBUDAJ)
	SET_PROTOCOL(EFFECT_ATTACK_ADVBUDAJ)
	SET_PROTOCOL(EFFECT_DIE_ADVBUDAJ)
	SET_PROTOCOL(EFFECT_SELECT_FARMERJ)			// 350

	SET_PROTOCOL(EFFECT_MOVE_FARMERJ)
	SET_PROTOCOL(EFFECT_DIE_FARMERJ)
	SET_PROTOCOL(EFFECT_SELECT_SWORDJ)
	SET_PROTOCOL(EFFECT_MOVE_SWORDJ)
	SET_PROTOCOL(EFFECT_ATTACK_SWORDJ)
	SET_PROTOCOL(EFFECT_DIE_SWORDJ)
	SET_PROTOCOL(EFFECT_SELECT_GUNJ)
	SET_PROTOCOL(EFFECT_MOVE_GUNJ)
	SET_PROTOCOL(EFFECT_ATTACK_GUNJ)
	SET_PROTOCOL(EFFECT_DIE_GUNJ)				// 360

	SET_PROTOCOL(EFFECT_SELECT_HORSESWORDJ)
	SET_PROTOCOL(EFFECT_MOVE_HORSESWORDJ)
	SET_PROTOCOL(EFFECT_ATTACK_HORSESWORDJ)
	SET_PROTOCOL(EFFECT_DIE_HORSESWORDJ)
	SET_PROTOCOL(EFFECT_SELECT_ELEPHANT)
	SET_PROTOCOL(EFFECT_ATTACK_ELEPHANT)
	SET_PROTOCOL(EFFECT_DIE_ELEPHANT)
	SET_PROTOCOL(EFFECT_DIE_SEAKING)
	SET_PROTOCOL(EFFECT_DIE_BEAR)
	SET_PROTOCOL(EFFECT_SELECT_BEAR)			// 370

	SET_PROTOCOL(EFFECT_ATTACK_BEAR)
	SET_PROTOCOL(EFFECT_HOSPITAL00)
	SET_PROTOCOL(EFFECT_HOSPITAL10)
	SET_PROTOCOL(EFFECT_HOSPITAL20)
	SET_PROTOCOL(EFFECT_HOSPITAL30)
	SET_PROTOCOL(EFFECT_HOSPITAL40)
	SET_PROTOCOL(EFFECT_BARRACK00)
	SET_PROTOCOL(EFFECT_BARRACK10)
	SET_PROTOCOL(EFFECT_GOV00)
	SET_PROTOCOL(EFFECT_GOV10)					// 380

	SET_PROTOCOL(EFFECT_GOV00T)
	SET_PROTOCOL(EFFECT_GOV10T)
	SET_PROTOCOL(EFFECT_USEITEM_POTION)
	SET_PROTOCOL(EFFECT_USEITEM_FRUIT)
	SET_PROTOCOL(EFFECT_USEITEM_SWORD)
	SET_PROTOCOL(EFFECT_USEITEM_HELMET)
	SET_PROTOCOL(EFFECT_USEITEM_MEET)
	SET_PROTOCOL(EFFECT_USEITEM_CLOTH)
	SET_PROTOCOL(EFFECT_USEITEM_ARMOUR)
	SET_PROTOCOL(EFFECT_USEITEM_WEAPON)			// 390

	SET_PROTOCOL(EFFECT_ON_GET_ITEM)
	SET_PROTOCOL(EFFECT_ON_DROP_ITEM)
	SET_PROTOCOL(EFFECT_ON_HEAL)
	SET_PROTOCOL(EFFECT_ON_DISMISS)
	SET_PROTOCOL(EFFECT_CANNOTENTERVILLAGE)
	SET_PROTOCOL(EFFECT_ITEMEQUIP0)
	SET_PROTOCOL(EFFECT_STARTBATTLE)
	SET_PROTOCOL(EFFECT_COUNTDOWN)
	SET_PROTOCOL(EFFECT_SETBATTLEMODE)
	SET_PROTOCOL(EFFECT_ONGHWAATTACK)			// 400

	SET_PROTOCOL(EFFECT_BUILD_WEAPONSHOP)
	SET_PROTOCOL(EFFECT_CLON)
	SET_PROTOCOL(EFFECT_FIRE_JUSTICEK)
	SET_PROTOCOL(EFFECT_ICEPALSY)
	SET_PROTOCOL(EFFECT_QUEST_ASIGN)
	SET_PROTOCOL(EFFECT_QUEST_CLEAR)
	SET_PROTOCOL(EFFECT_TUTTLEWAVE)
	SET_PROTOCOL(EFFECT_SELECT_SEAHORSE)
	SET_PROTOCOL(EFFECT_DIE_SEAHORSE)
	SET_PROTOCOL(EFFECT_SELECT_CAT)				// 410

	SET_PROTOCOL(EFFECT_DIE_CAT)
	SET_PROTOCOL(EFFECT_FIRE_CAT)
	SET_PROTOCOL(EFFECT_SELECT_DUCK)
	SET_PROTOCOL(EFFECT_DIE_DUCK)
	SET_PROTOCOL(EFFECT_FIRE_DUCK)
	SET_PROTOCOL(EFFECT_SELECT_HORNET)
	SET_PROTOCOL(EFFECT_DIE_HORNET)
	SET_PROTOCOL(EFFECT_SELECT_SWORDPIRATE)
	SET_PROTOCOL(EFFECT_ATTACK_SWORDPIRATE)
	SET_PROTOCOL(EFFECT_SELECT_GUNPIRATE)		// 420

	SET_PROTOCOL(EFFECT_ATTACK_GUNPIRATE)
	SET_PROTOCOL(EFFECT_SELECT_ONI)
	SET_PROTOCOL(EFFECT_ATTACK_ONI)
	SET_PROTOCOL(EFFECT_SELECT_SNOWWOMAN)
	SET_PROTOCOL(EFFECT_ATTACK_SNOWWOMAN)
	SET_PROTOCOL(EFFECT_MINIGAME1_START)
	SET_PROTOCOL(EFFECT_MINIGAME1_TIME)
	SET_PROTOCOL(EFFECT_MINIGAME1_CARD)
	SET_PROTOCOL(EFFECT_MINIGAME1_CARDCOVER)
	SET_PROTOCOL(EFFECT_MINIGAME1_PAIR)			// 430

	SET_PROTOCOL(EFFECT_MINIGAME3_FRUITOK)
	SET_PROTOCOL(EFFECT_MINIGAME3_FRUITFAIL)
	SET_PROTOCOL(EFFECT_GETCASTLE)
	SET_PROTOCOL(EFFECT_ON_DIE_BOGY)
	SET_PROTOCOL(EFFECT_TRY_BOGY)
	SET_PROTOCOL(EFFECT_ON_DIE_SNOWWOMAN)
	SET_PROTOCOL(EFFECT_TRY_SNOWWOMAN)
	SET_PROTOCOL(EFFECT_ON_DIE_FOX)
	SET_PROTOCOL(EFFECT_TRY_FOX)
	SET_PROTOCOL(EFFECT_SELECT_NINJAJ)			// 440

	SET_PROTOCOL(EFFECT_MOVE_NINJAJ)
	SET_PROTOCOL(EFFECT_ATTACK_NINJAJ)
	SET_PROTOCOL(EFFECT_DIE_NINJAJ)
	SET_PROTOCOL(EFFECT_SELECT_CHAWOO)
	SET_PROTOCOL(EFFECT_ATTACK_CHAWOO)
	SET_PROTOCOL(EFFECT_DIE_CHAWOO)
	SET_PROTOCOL(EFFECT_SELECT_WILDBOAR)
	SET_PROTOCOL(EFFECT_ATTACK_WILDBOAR)
	SET_PROTOCOL(EFFECT_DIE_WILDBOAR)
	SET_PROTOCOL(EFFECT_SELECT_GANGSI)			// 450

	SET_PROTOCOL(EFFECT_ATTACK_GANGSI)
	SET_PROTOCOL(EFFECT_DIE_GANGSI)
	SET_PROTOCOL(EFFECT_SELECT_BABARIAN)
	SET_PROTOCOL(EFFECT_SELECT_BSHAMAN)
	SET_PROTOCOL(EFFECT_SELECT_NPC_HONG)
	SET_PROTOCOL(EFFECT_SELECT_GENERAL1T)
	SET_PROTOCOL(EFFECT_MOVE_GENERAL1T)
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL1T)
	SET_PROTOCOL(EFFECT_DIE_GENERAL1T)
	SET_PROTOCOL(EFFECT_SELECT_GENERAL4T)		// 460

	SET_PROTOCOL(EFFECT_MOVE_GENERAL4T)
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL4T)
	SET_PROTOCOL(EFFECT_DIE_GENERAL4T)
	SET_PROTOCOL(EFFECT_SELECT_PORTERT)
	SET_PROTOCOL(EFFECT_MOVE_PORTERT)
	SET_PROTOCOL(EFFECT_ATTACK_PORTERT)
	SET_PROTOCOL(EFFECT_DIE_PORTERT)
	SET_PROTOCOL(EFFECT_SELECT_AXET)
	SET_PROTOCOL(EFFECT_MOVE_AXET)
	SET_PROTOCOL(EFFECT_ATTACK_AXET)			// 470

	SET_PROTOCOL(EFFECT_DIE_AXET)
	SET_PROTOCOL(EFFECT_SELECT_GUNT)
	SET_PROTOCOL(EFFECT_MOVE_GUNT)
	SET_PROTOCOL(EFFECT_ATTACK_GUNT)
	SET_PROTOCOL(EFFECT_DIE_GUNT)
	SET_PROTOCOL(EFFECT_SELECT_BUDAT)
	SET_PROTOCOL(EFFECT_MOVE_BUDAT)
	SET_PROTOCOL(EFFECT_ATTACK_BUDAT)
	SET_PROTOCOL(EFFECT_DIE_BUDAT)
	SET_PROTOCOL(EFFECT_SELECT_SWORDT)			// 480

	SET_PROTOCOL(EFFECT_MOVE_SWORDT)
	SET_PROTOCOL(EFFECT_ATTACK_SWORDT)
	SET_PROTOCOL(EFFECT_DIE_SWORDT)
	SET_PROTOCOL(EFFECT_SELECT_GENERAL2T)
	SET_PROTOCOL(EFFECT_MOVE_GENERAL2T)
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL2T)
	SET_PROTOCOL(EFFECT_DIE_GENERAL2T)
	SET_PROTOCOL(EFFECT_SELECT_GENERAL3T)
	SET_PROTOCOL(EFFECT_MOVE_GENERAL3T)
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL3T)		// 490

	SET_PROTOCOL(EFFECT_DIE_GENERAL3T)
	SET_PROTOCOL(EFFECT_SELECT_AMAZONT)
	SET_PROTOCOL(EFFECT_MOVE_AMAZONT)
	SET_PROTOCOL(EFFECT_ATTACK_AMAZONT)
	SET_PROTOCOL(EFFECT_DIE_AMAZONT)
	SET_PROTOCOL(EFFECT_SELECT_GENERAL5T)
	SET_PROTOCOL(EFFECT_MOVE_GENERAL5T)
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL5T)
	SET_PROTOCOL(EFFECT_DIE_GENERAL5T)
	SET_PROTOCOL(EFFECT_HOSPITAL00T)			// 500

	SET_PROTOCOL(EFFECT_HOSPITAL10T)
	SET_PROTOCOL(EFFECT_HOSPITAL20T)
	SET_PROTOCOL(EFFECT_HOSPITAL30T)
	SET_PROTOCOL(EFFECT_HOSPITAL40T)
	SET_PROTOCOL(EFFECT_SELECT_FANC)
	SET_PROTOCOL(EFFECT_MOVE_FANC)
	SET_PROTOCOL(EFFECT_ATTACK_FANC)
	SET_PROTOCOL(EFFECT_DIE_FANC)
	SET_PROTOCOL(EFFECT_SELECT_PORTERC)
	SET_PROTOCOL(EFFECT_MOVE_PORTERC)			// 510

	SET_PROTOCOL(EFFECT_DIE_PORTERC)				
	SET_PROTOCOL(EFFECT_SELECT_MUDOGAC)			
	SET_PROTOCOL(EFFECT_MOVE_MUDOGAC)				
	SET_PROTOCOL(EFFECT_ATTACK_MUDOGAC)		
	SET_PROTOCOL(EFFECT_DIE_MUDOGAC)			
	SET_PROTOCOL(EFFECT_SELECT_BUDAKC)			
	SET_PROTOCOL(EFFECT_MOVE_BUDAKC)			
	SET_PROTOCOL(EFFECT_ATTACK_BUDAKC)			
	SET_PROTOCOL(EFFECT_DIE_BUDAKC)				
	SET_PROTOCOL(EFFECT_SELECT_BIGSWORDC)		// 520			

	SET_PROTOCOL(EFFECT_MOVE_BIGSWORDC)			
	SET_PROTOCOL(EFFECT_ATTACK_BIGSWORDC)			
	SET_PROTOCOL(EFFECT_DIE_BIGSWORDC)			
	SET_PROTOCOL(EFFECT_SELECT_FIREGUNC)		
	SET_PROTOCOL(EFFECT_MOVE_FIREGUNC)			
	SET_PROTOCOL(EFFECT_ATTACK_FIREGUNC)			
	SET_PROTOCOL(EFFECT_DIE_FIREGUNC)				
	SET_PROTOCOL(EFFECT_DIE_GENERAL_C1)			
	SET_PROTOCOL(EFFECT_DIE_GENERAL_C3)			
	SET_PROTOCOL(EFFECT_DIE_GENERAL_C4)			// 530			

	SET_PROTOCOL(EFFECT_DIE_GENERAL_C5)			
	SET_PROTOCOL(EFFECT_DIE_GENERALJ2)			
	SET_PROTOCOL(EFFECT_DIE_GENERALJ3)			
	SET_PROTOCOL(EFFECT_DIE_GENERALJ4)			
	SET_PROTOCOL(EFFECT_DIE_GENERALJ6)			
	SET_PROTOCOL(EFFECT_DIE_GENERALJ8)			
	SET_PROTOCOL(EFFECT_SELECT_SMALLGANG)			
	SET_PROTOCOL(EFFECT_SELECT_MBANDIT3)		
	SET_PROTOCOL(EFFECT_ATTACK_MBANDIT3)			
	SET_PROTOCOL(EFFECT_SELECT_PIRATES)			// 540			

	SET_PROTOCOL(EFFECT_ATTACK_PIRATES)			
	SET_PROTOCOL(EFFECT_SELECT_SEAKING)			
	SET_PROTOCOL(EFFECT_ATTACK_SEAKING)			
	SET_PROTOCOL(EFFECT_SELECT_MBANDIT1)			
	SET_PROTOCOL(EFFECT_ATTACK_MBANDIT1)		
	SET_PROTOCOL(EFFECT_HOSPITAL00J)				
	SET_PROTOCOL(EFFECT_HOSPITAL10J)				
	SET_PROTOCOL(EFFECT_HOSPITAL20J)			
	SET_PROTOCOL(EFFECT_HOSPITAL30J)				
	SET_PROTOCOL(EFFECT_HOSPITAL40J)			// 550				

	SET_PROTOCOL(EFFECT_GOV00J)
	SET_PROTOCOL(EFFECT_GOV10J)					
	SET_PROTOCOL(EFFECT_BARRACK00J)				
	SET_PROTOCOL(EFFECT_BARRACK10J)				
	SET_PROTOCOL(EFFECT_SELECT_BIGTREE)			
	SET_PROTOCOL(EFFECT_ATTACK_BIGTREE)			
	SET_PROTOCOL(EFFECT_DIE_BIGTREE)				
	SET_PROTOCOL(EFFECT_SELECT_CACTUS)			
	SET_PROTOCOL(EFFECT_ATTACK_CACTUS)			
	SET_PROTOCOL(EFFECT_DIE_CACTUS)				// 560				

	SET_PROTOCOL(EFFECT_SELECT_SNAKE)				
	SET_PROTOCOL(EFFECT_ATTACK_SNAKE)				
	SET_PROTOCOL(EFFECT_DIE_SNAKE)				
	SET_PROTOCOL(EFFECT_SELECT_SCORPION)			
	SET_PROTOCOL(EFFECT_ATTACK_SCORPION)		
	SET_PROTOCOL(EFFECT_DIE_SCORPION)				
	SET_PROTOCOL(EFFECT_SELECT_HORSEMAN)			
	SET_PROTOCOL(EFFECT_ATTACK_HORSEMAN)			
	SET_PROTOCOL(EFFECT_DIE_HORSEMAN)			
	SET_PROTOCOL(EFFECT_SELECT_SANDGOD)			// 570			

	SET_PROTOCOL(EFFECT_ATTACK_SANDGOD)			
	SET_PROTOCOL(EFFECT_DIE_SANDGOD)			
	SET_PROTOCOL(EFFECT_SELECT_SEAENVOY)			
	SET_PROTOCOL(EFFECT_ATTACK_SEAENVOY)		
	SET_PROTOCOL(EFFECT_DIE_SEAENVOY)			
	SET_PROTOCOL(EFFECT_SELECT_SNOWDEMON)			
	SET_PROTOCOL(EFFECT_ATTACK_SNOWDEMON)			
	SET_PROTOCOL(EFFECT_DIE_SNOWDEMON)		
	SET_PROTOCOL(EFFECT_SELECT_CROCODILE)			
	SET_PROTOCOL(EFFECT_ATTACK_CROCODILE)		// 580			

	SET_PROTOCOL(EFFECT_DIE_CROCODILE)		
	SET_PROTOCOL(EFFECT_SELECT_LAVAMONSTER)		
	SET_PROTOCOL(EFFECT_ATTACK_LAVAMONSTER)	
	SET_PROTOCOL(EFFECT_DIE_LAVAMONSTER)		
	SET_PROTOCOL(EFFECT_SELECT_EVIL)		
	SET_PROTOCOL(EFFECT_ATTACK_EVIL)			
	SET_PROTOCOL(EFFECT_DIE_EVIL)				
	SET_PROTOCOL(EFFECT_ATTACK_WEASEL)		
	SET_PROTOCOL(EFFECT_DIE_WEASEL)			
	SET_PROTOCOL(EFFECT_SELECT_SOUL)			// 590				

	SET_PROTOCOL(EFFECT_ATTACK_SOUL)			
	SET_PROTOCOL(EFFECT_DIE_SOUL)				
	SET_PROTOCOL(EFFECT_SELECT_COBRA)				
	SET_PROTOCOL(EFFECT_ATTACK_COBRA)				
	SET_PROTOCOL(EFFECT_DIE_COBRA)			
	SET_PROTOCOL(EFFECT_SELECT_PANDA)				
	SET_PROTOCOL(EFFECT_ATTACK_PANDA)				
	SET_PROTOCOL(EFFECT_DIE_PANDA)			
	SET_PROTOCOL(EFFECT_SELECT_VOLCANOFLAME)
	SET_PROTOCOL(EFFECT_ATTACK_VOLCANOFLAME)	// 600

	SET_PROTOCOL(EFFECT_DIE_VOLCANOFLAME)		
	SET_PROTOCOL(EFFECT_SELECT_MADBULL)		
	SET_PROTOCOL(EFFECT_ATTACK_MADBULL)			
	SET_PROTOCOL(EFFECT_DIE_MADBULL)			
	SET_PROTOCOL(EFFECT_SELECT_BIRD)			
	SET_PROTOCOL(EFFECT_ATTACK_BIRD)			
	SET_PROTOCOL(EFFECT_DIE_BIRD)				
	SET_PROTOCOL(EFFECT_SELECT_KOREANGHOST)
	SET_PROTOCOL(EFFECT_ATTACK_KOREANGHOST)		
	SET_PROTOCOL(EFFECT_DIE_KOREANGHOST)		// 610		

	SET_PROTOCOL(EFFECT_SELECT_GACKDAGUI)			
	SET_PROTOCOL(EFFECT_ATTACK_GACKDAGUI)			
	SET_PROTOCOL(EFFECT_SELECT_RUNNERHAND)		
	SET_PROTOCOL(EFFECT_DIE_RUNNERHAND)		
	SET_PROTOCOL(EFFECT_ATTACK_RUNNERHAND)		
	SET_PROTOCOL(EFFECT_SELECT_DOGDEMON)	
	SET_PROTOCOL(EFFECT_ATTACK_DOGDEMON)		
	SET_PROTOCOL(EFFECT_SELECT_GHOSTCAT)		
	SET_PROTOCOL(EFFECT_DIE_GHOSTCAT)			
	SET_PROTOCOL(EFFECT_ATTACK_GHOSTCAT)		// 620

	SET_PROTOCOL(EFFECT_ATTACK_RACOONDOG)			
	SET_PROTOCOL(EFFECT_SELECT_RACOONDOG)			
	SET_PROTOCOL(EFFECT_ATTACK_SNOWLIZARD)		
	SET_PROTOCOL(EFFECT_SELECT_SNOWLIZARD)		
	SET_PROTOCOL(EFFECT_DIE_SNOWLIZARD)		
	SET_PROTOCOL(EFFECT_ATTACK_DUCK)			
	SET_PROTOCOL(EFFECT_ATTACK_HORNET)			
	SET_PROTOCOL(EFFECT_ATTACK_CAT)			
	SET_PROTOCOL(EFFECT_DIE_BUTTERFLY)			
	SET_PROTOCOL(EFFECT_ATTACK_BUTTERFLY)		// 630
	
	SET_PROTOCOL(EFFECT_SELECT_BUTTERFLY)			
	SET_PROTOCOL(EFFECT_SELECT_TOAD)			
	SET_PROTOCOL(EFFECT_DIE_TOAD)				
	SET_PROTOCOL(EFFECT_ATTACK_TOAD)				
	SET_PROTOCOL(EFFECT_SELECT_CENTIPEDE)		
	SET_PROTOCOL(EFFECT_ATTACK_CENTIPEDE)			
	SET_PROTOCOL(EFFECT_ATTACK_HARUBANG)		
	SET_PROTOCOL(EFFECT_SELECT_HARUBANG)		
	SET_PROTOCOL(EFFECT_DIE_HARUBANG)				
	SET_PROTOCOL(EFFECT_ATTACK_DUEOKSINI)		// 640

	SET_PROTOCOL(EFFECT_SELECT_DUEOKSINI)			
	SET_PROTOCOL(EFFECT_DIE_DUEOKSINI)		
	SET_PROTOCOL(EFFECT_SELECT_WORRIORGHOST)		
	SET_PROTOCOL(EFFECT_ATTACK_WORRIORGHOST)	
	SET_PROTOCOL(EFFECT_DIE_WORRIORGHOST)		
	SET_PROTOCOL(EFFECT_SELECT_TUTTLE)		
	SET_PROTOCOL(EFFECT_ATTACK_TUTTLE)			
	SET_PROTOCOL(EFFECT_DIE_TUTTLE)			
	SET_PROTOCOL(EFFECT_SELECT_CRAB)				
	SET_PROTOCOL(EFFECT_ATTACK_CRAB)			// 650			

	SET_PROTOCOL(EFFECT_DIE_CRAB)				
	SET_PROTOCOL(EFFECT_SELECT_WIDOW)			
	SET_PROTOCOL(EFFECT_ATTACK_WIDOW)				
	SET_PROTOCOL(EFFECT_DIE_WIDOW)			
	SET_PROTOCOL(EFFECT_ATTACK_BAT)				
	SET_PROTOCOL(EFFECT_SELECT_BAT)				
	SET_PROTOCOL(EFFECT_SELECT_WHITETIGER)	
	SET_PROTOCOL(EFFECT_ATTACK_WHITETIGER)		
	SET_PROTOCOL(EFFECT_DIE_WHITETIGER)		
	SET_PROTOCOL(EFFECT_SELECT_STARFISH)		// 660

	SET_PROTOCOL(EFFECT_ATTACK_STARFISH)		
	SET_PROTOCOL(EFFECT_SELECT_INSECT)		
	SET_PROTOCOL(EFFECT_ATTACK_INSECT)			
	SET_PROTOCOL(EFFECT_DIE_INSECT)			
	SET_PROTOCOL(EFFECT_SELECT_DEER)				
	SET_PROTOCOL(EFFECT_ATTACK_DEER)			
	SET_PROTOCOL(EFFECT_SELECT_VIPER)			
	SET_PROTOCOL(EFFECT_ATTACK_VIPER)				
	SET_PROTOCOL(EFFECT_DIE_VIPER)			
	SET_PROTOCOL(EFFECT_DIE_SNOWWOMAN)			// 670

	SET_PROTOCOL(EFFECT_ATTACK_EATERDEMON)	
	SET_PROTOCOL(EFFECT_SELECT_EATERDEMON)		
	SET_PROTOCOL(EFFECT_ATTACK_SINGERMGHOST)		
	SET_PROTOCOL(EFFECT_SELECT_SINGERMGHOST)	
	SET_PROTOCOL(EFFECT_DIE_SINGERMGHOST)			
	SET_PROTOCOL(EFFECT_ATTACK_HUNGRYDEMON)	
	SET_PROTOCOL(EFFECT_SELECT_HUNGRYDEMON)		
	SET_PROTOCOL(EFFECT_DIE_HUNGRYDEMON)		
	SET_PROTOCOL(EFFECT_ATTACK_ICETREE)		
	SET_PROTOCOL(EFFECT_SELECT_ICETREE)			// 680

	SET_PROTOCOL(EFFECT_DIE_ICETREE)
	SET_PROTOCOL(EFFECT_DIE_ONI)			
	SET_PROTOCOL(EFFECT_ATTACK_LEECH)
	SET_PROTOCOL(EFFECT_SELECT_LEECH)				
	SET_PROTOCOL(EFFECT_DIE_LEECH)			
	SET_PROTOCOL(EFFECT_ATTACK_MAGICIAN)
	SET_PROTOCOL(EFFECT_SELECT_MAGICIAN)
	SET_PROTOCOL(EFFECT_DIE_MAGICIAN)
	SET_PROTOCOL(EFFECT_ATTACK_BABARIANSHAMAN)
	SET_PROTOCOL(EFFECT_SELECT_BABARIANSHAMAN)	// 690

	SET_PROTOCOL(EFFECT_DIE_BABARIANSHAMAN)
	SET_PROTOCOL(EFFECT_ATTACK_SMALLGANG)
	SET_PROTOCOL(EFFECT_DIE_SMALLGANG)
	SET_PROTOCOL(EFFECT_ATTACK_FURHEADDEMON)
	SET_PROTOCOL(EFFECT_SELECT_FURHEADDEMON)
	SET_PROTOCOL(EFFECT_ATTACK_TIGER)
	SET_PROTOCOL(EFFECT_SELECT_TIGER)
	SET_PROTOCOL(EFFECT_DIE_TIGER)
	SET_PROTOCOL(EFFECT_ATTACK_FIREDRAGON)
	SET_PROTOCOL(EFFECT_SELECT_FIREDRAGON)		// 700

	SET_PROTOCOL(EFFECT_ATTACK_GOLDDRAGON)
	SET_PROTOCOL(EFFECT_SELECT_GOLDDRAGON)
	SET_PROTOCOL(EFFECT_DIE_PIRATES)
	SET_PROTOCOL(EFFECT_ATTACK_SEAHORSE)
	SET_PROTOCOL(EFFECT_ATTACK_BANDIT1)
	SET_PROTOCOL(EFFECT_DIE_SWORDPIRATE)
	SET_PROTOCOL(EFFECT_DIE_BABARIAN)
	SET_PROTOCOL(EFFECT_DIE_MBANDIT3)
	SET_PROTOCOL(EFFECT_SELECT_WEASEL)
	SET_PROTOCOL(EFFECT_DIE_GUNPIRATE)			// 710

	SET_PROTOCOL(EFFECT_ATTACK_HOOK)				
	SET_PROTOCOL(EFFECT_DIE_HOOK)				
	SET_PROTOCOL(EFFECT_ATTACK_SKYNINE)
	SET_PROTOCOL(EFFECT_DIE_SKYNINE)
	SET_PROTOCOL(EFFECT_ATTACK_HORSESPEAR)
	SET_PROTOCOL(EFFECT_DIE_HORSESPEAR)
	SET_PROTOCOL(EFFECT_ATTACK_THIEF)				
	SET_PROTOCOL(EFFECT_DIE_THIEF)		
	SET_PROTOCOL(EFFECT_ATTACK_MBANDIT2)
	SET_PROTOCOL(EFFECT_DIE_MBANDIT2)			// 720			

	SET_PROTOCOL(EFFECT_ATTACK_AMAKUSA)
	SET_PROTOCOL(EFFECT_DIE_AMAKUSA)			
	SET_PROTOCOL(EFFECT_ATTACK_BADMERCHANT)
	SET_PROTOCOL(EFFECT_DIE_BADMERCHANT)		
	SET_PROTOCOL(EFFECT_ATTACK_BOGY)		
	SET_PROTOCOL(EFFECT_ATTACK_BANDIT2)
	SET_PROTOCOL(EFFECT_ATTACK_BANDIT3)
	SET_PROTOCOL(EFFECT_ATTACK_FOX)
	SET_PROTOCOL(EFFECT_ATTACK_GATPHA)
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_C1_EXT)	// 730

	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_C2_EXT)	
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_C3_EXT)	
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_C4_EXT)	
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_C5_EXT)	
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_T1_EXT)	
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_T2_EXT)	
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_T3_EXT)	
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_T4_EXT)	
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_T5_EXT)	
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_J6_EXT)	// 740	

	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_J4_EXT)	
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_J8_EXT)	
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_K8_EXT)	
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_K8_EXT2)	
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_K3_EXT)	
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_K2_EXT)	
	SET_PROTOCOL(EFFECT_ATTACK_GENERAL_K5_EXT)	
	SET_PROTOCOL(EFFECT_SELECT_SKYNINE)	
	SET_PROTOCOL(EFFECT_SELECT_AMAKUSA)		
	SET_PROTOCOL(EFFECT_SELECT_HOOK)			// 750			

	SET_PROTOCOL(EFFECT_DIE_GENERALK5)
	SET_PROTOCOL(EFFECT_DIE_GENERALK2)
	SET_PROTOCOL(EFFECT_DIE_GENERALK8)
	SET_PROTOCOL(EFFECT_DIE_GENERALK4)
	SET_PROTOCOL(EFFECT_DIE_GENERALK3)
	SET_PROTOCOL(EFFECT_ARMOR_CLOTH)
	SET_PROTOCOL(EFFECT_ARMOR_METAL)
	SET_PROTOCOL(EFFECT_ARMOR_RARE)
	SET_PROTOCOL(EFFECT_ARMOR_WOODEN)
	SET_PROTOCOL(EFFECT_BELT_CLOTH)				// 760			

	SET_PROTOCOL(EFFECT_BELT_METAL)
	SET_PROTOCOL(EFFECT_BELT_RARE)
	SET_PROTOCOL(EFFECT_GLOVE_CLOTH)
	SET_PROTOCOL(EFFECT_GLOVE_METAL)
	SET_PROTOCOL(EFFECT_GLOVE_RARE)
	SET_PROTOCOL(EFFECT_GLOVE_WOODEN)
	SET_PROTOCOL(EFFECT_HELMET_CLOTH)
	SET_PROTOCOL(EFFECT_HELMET_METAL)
	SET_PROTOCOL(EFFECT_HELMET_RARE)
	SET_PROTOCOL(EFFECT_HELMET_WOODEN)			// 770

	SET_PROTOCOL(EFFECT_HELMET_HAT)
	SET_PROTOCOL(EFFECT_SHOES_CLOTH)
	SET_PROTOCOL(EFFECT_SHOES_ETC)
	SET_PROTOCOL(EFFECT_SHOES_METAL)
	SET_PROTOCOL(EFFECT_SHOES_WOODEN)
	SET_PROTOCOL(EFFECT_WEAPON_DART)
	SET_PROTOCOL(EFFECT_WEAPON_GUN)
	SET_PROTOCOL(EFFECT_WEAPON_ARROW)
	SET_PROTOCOL(EFFECT_WEAPON_RING)
	SET_PROTOCOL(EFFECT_WEAPON_SWORD)			// 780

	SET_PROTOCOL(EFFECT_WEAPON_WOODEN)
	SET_PROTOCOL(EFFECT_ETC)
	SET_PROTOCOL(EFFECT_ATTACK_TIRANO)
	SET_PROTOCOL(EFFECT_DIE_TIRANO)
	SET_PROTOCOL(EFFECT_ATTACK_RAPTOR)
	SET_PROTOCOL(EFFECT_DIE_RAPTOR)
	SET_PROTOCOL(EFFECT_ATTACK_FLYDRAGON)
	SET_PROTOCOL(EFFECT_DIE_FLYDRAGON)
	SET_PROTOCOL(EFFECT_ATTACK_CLAYFIGURE)
	SET_PROTOCOL(EFFECT_DIE_CLAYFIGURE)			// 790

	SET_PROTOCOL(EFFECT_SELECT_CLAYFIGURE)
	SET_PROTOCOL(EFFECT_ATTACK_GATEKEEPER)
	SET_PROTOCOL(EFFECT_DIE_GATEKEEPER)
	SET_PROTOCOL(EFFECT_SELECT_GATEKEEPER)
	SET_PROTOCOL(EFFECT_ATTACK_PHOENIX)
	SET_PROTOCOL(EFFECT_DIE_PHOENIX)
	SET_PROTOCOL(EFFECT_SELECT_PHOENIX)
	SET_PROTOCOL(EFFECT_ATTACK_HELLKING)
	SET_PROTOCOL(EFFECT_DIE_HELLKING)
	SET_PROTOCOL(EFFECT_SELECT_HELLKING)		// 800

	SET_PROTOCOL(EFFECT_ATTACK_GHOSTSAMURAI)
	SET_PROTOCOL(EFFECT_DIE_GHOSTSAMURAI)
	SET_PROTOCOL(EFFECT_SELECT_GHOSTSAMURAI)
	SET_PROTOCOL(EFFECT_ATTACK_PYTHON)
	SET_PROTOCOL(EFFECT_DIE_PYTHON)
	SET_PROTOCOL(EFFECT_SELECT_PYTHON)
	SET_PROTOCOL(EFFECT_ATTACK_HELLMESSENGER)
	SET_PROTOCOL(EFFECT_DIE_HELLMESSENGER)
	SET_PROTOCOL(EFFECT_SELECT_HELLMESSENGER)
	SET_PROTOCOL(EFFECT_ATTACK_JINEMPEROR)		// 810

	SET_PROTOCOL(EFFECT_DIE_JINEMPEROR)
	SET_PROTOCOL(EFFECT_SELECT_JINEMPEROR)
	SET_PROTOCOL(EFFECT_GUARDIAN_MOUSE_RECALL)
	SET_PROTOCOL(EFFECT_GUARDIAN_MOUSE_ATTACK)
	SET_PROTOCOL(EFFECT_GUARDIAN_MOUSE_DIE)
	SET_PROTOCOL(EFFECT_GUARDIAN_CAW_RECALL)
	SET_PROTOCOL(EFFECT_GUARDIAN_CAW_RECALL2)
	SET_PROTOCOL(EFFECT_GUARDIAN_CAW_ATTACK1)
	SET_PROTOCOL(EFFECT_GUARDIAN_CAW_ATTACK2)
	SET_PROTOCOL(EFFECT_GUARDIAN_CAW_ATTACK3)	// 820

	SET_PROTOCOL(EFFECT_GUARDIAN_CAW_DIE1)
	SET_PROTOCOL(EFFECT_GUARDIAN_CAW_DIE2)
	SET_PROTOCOL(EFFECT_GUARDIAN_CAW_DIE3)
	SET_PROTOCOL(EFFECT_GUARDIAN_TIGER_ATTACK)
	SET_PROTOCOL(EFFECT_GUARDIAN_TIGER_END)
	SET_PROTOCOL(EFFECT_GUARDIAN_DRAGON_ATTACK)
	SET_PROTOCOL(EFFECT_GUARDIAN_HORSE_ATTACK)
	SET_PROTOCOL(EFFECT_GUARDIAN_HORSE_END)
	SET_PROTOCOL(EFFECT_GUARDIAN_RABBIT_ATTACK)
	SET_PROTOCOL(EFFECT_GUARDIAN_RABBIT_END)	// 830

	SET_PROTOCOL(EFFECT_GUARDIAN_SNAKE_RECALL)
	SET_PROTOCOL(EFFECT_GUARDIAN_SHEEP_ATTACK)
	SET_PROTOCOL(EFFECT_GUARDIAN_MONKEY_RECALL)
	SET_PROTOCOL(EFFECT_GUARDIAN_MONKEY_ATTACK)
	SET_PROTOCOL(EFFECT_GUARDIAN_MONKEY_DIE)
	SET_PROTOCOL(EFFECT_GUARDIAN_CHICK_RECALL)
	SET_PROTOCOL(EFFECT_GUARDIAN_CHICK_ATTACK)
	SET_PROTOCOL(EFFECT_GUARDIAN_CHICK_DIE)
	SET_PROTOCOL(EFFECT_GUARDIAN_DOG_ATTACK)
	SET_PROTOCOL(EFFECT_GUARDIAN_PIG_RECALL)	// 840

	SET_PROTOCOL(EFFECT_GUARDIAN_PIG_ATTACK)
	SET_PROTOCOL(EFFECT_GUARDIAN_PIG_DIE)

	SET_PROTOCOL(EFFECT_SMALLGANG_C)
	SET_PROTOCOL(EFFECT_HOSPITAL_C)
	SET_PROTOCOL(EFFECT_DIE_HOSPITAL_C)
	SET_PROTOCOL(EFFECT_TEAM1_C)
	SET_PROTOCOL(EFFECT_TEAM2_C)
	SET_PROTOCOL(EFFECT_TEAM3_C)
	SET_PROTOCOL(EFFECT_TEAM4_C)
	SET_PROTOCOL(EFFECT_TEAM5_C)				// 850
	SET_PROTOCOL(EFFECT_TEAM6_C)
	SET_PROTOCOL(EFFECT_TEAM7_C)
	SET_PROTOCOL(EFFECT_TEAM8_C)
	SET_PROTOCOL(EFFECT_TEAM9_C)
	SET_PROTOCOL(EFFECT_TEAM10_C)
	SET_PROTOCOL(EFFECT_MBARRACK_C)
	SET_PROTOCOL(EFFECT_BARRACK_C)
	SET_PROTOCOL(EFFECT_NOT_HOSPITAL_C)
	SET_PROTOCOL(EFFECT_FOOD_VEGETABLE)
	SET_PROTOCOL(EFFECT_FOOD_TEA)				// 860
	SET_PROTOCOL(EFFECT_FOOD_SPECIAL)
	SET_PROTOCOL(EFFECT_FOOD_NUDDLE)
	SET_PROTOCOL(EFFECT_FOOD_MEAT)
	SET_PROTOCOL(EFFECT_FOOD_FRUITS)
	SET_PROTOCOL(EFFECT_FOOD_ETC)

	// robypark 2004/6/22 17:30
	// 2차 장수 공격관련 효과음
	SET_PROTOCOL(EFFECT_FIRE_KU102AE1)	// 거북차 무기 발사 효과음
	SET_PROTOCOL(EFFECT_EXP_KU102AE2)	// 거북차 총알 폭발 효과음
	SET_PROTOCOL(EFFECT_FIRE_KU103AE2)	// 뇌전차 번개 발사 효과음
	SET_PROTOCOL(EFFECT_FIRE_JU104AE1)	// 지진차 발사 효과음
	SET_PROTOCOL(EFFECT_EXP_JU104AE2)	// 870 // 지진차 지진 효과음
	SET_PROTOCOL(EFFECT_FIRE_JU105AE1)	// 흑룡차 발사 효과음
	SET_PROTOCOL(EFFECT_EXP_JU105AE2)	// 흑룡차 폭발 효과음
	SET_PROTOCOL(EFFECT_FIRE_CU106AE1)	// 발석거 발사 효과음
	SET_PROTOCOL(EFFECT_EXP_CU106AE2)	// 발석거 총알 폭발 효과음
	SET_PROTOCOL(EFFECT_FIRE_CU107AE1)	// 불랑기포차 발사 효과음
	SET_PROTOCOL(EFFECT_EXP_CU107AE2)	// 불랑기포차 총알 폭발 효과음
	SET_PROTOCOL(EFFECT_FIRE_TU108AE1)	// 화룡차 창 공격 효과음
	SET_PROTOCOL(EFFECT_FIRE_TU108AE2)	// 화룡차 총알 발사 효과음
	SET_PROTOCOL(EFFECT_EXP_TU108AE3)	// 화룡차 총알 폭발 효과음
	SET_PROTOCOL(EFFECT_FIRE_TU109AE1)	// 880 // 봉황비조 발사 효과음
	SET_PROTOCOL(EFFECT_EXP_TU109AE2)	// 봉황비조 총알 폭발 효과음

	// robypark 2004/12/17 15:56 공성전 효과음 추가										
	// 칼 소리,		쨍쨍 거리는 칼등이 서로 부딫히는 소리
	SET_PROTOCOL(EFFECT_BLADEATTACK	)
	// 활 쏘는 소리		활을 쏘는 소리	
	SET_PROTOCOL(EFFECT_BOWATTACK	)
	// 발석거 돌 쏠때 소리		발석거가 돌을 쏠 때 소리
	SET_PROTOCOL(EFFECT_CATAPULTATTACK	)
	//충차 공격 소리		충차가(성벽을 부수는 기계) 공격 하는 소리
	SET_PROTOCOL(EFFECT_WALLBREAKERATTACK	)
	// 칼 맞을 때		칼에 맞았을 떄 베이는 소리
	SET_PROTOCOL(EFFECT_BLADEHIT	)
	// 활 맞을 떄		활을 맞았을 때 화살이 박히는 소리
	SET_PROTOCOL(EFFECT_BOWHIT	)
	// 발석거에게 맞을 때		발석거의 돌에 맞았을 때 소리
	SET_PROTOCOL(EFFECT_CATAPULTHIT	)
	// 충차에게 맞을 때	창칼 맞을 때와 같은 그림이나 소리는 다르게 나야함.(충차 그림에 함꼐 표시됨)	성벽이 충차에게 두들겨 맞을 때 소리
	SET_PROTOCOL(EFFECT_WALLBREAKERHIT	)
	// 창 공격 소리
	SET_PROTOCOL(EFFECT_SPEARATTACK	)	// 890
	// 창에 맞는 소리
	SET_PROTOCOL(EFFECT_SPEARHIT	)
	// 방어력 향상 소리	그림 제작중	성벽의 방어력을 향상하는 소리
	SET_PROTOCOL(EFFECT_WALLREPAIR	)
	// 인간 부대 이동시		검병, 창병, 궁병의 부대가 이동할 때 내는 기합소리
	SET_PROTOCOL(EFFECT_ARMYMOVE	)
	// 기마병 부대 이동시		기마병 부대가 이동할 때 나는 말 발굽 소리
	SET_PROTOCOL(EFFECT_CAVALRYMOVE	)
	// 발석거 이동시		발석거가 이동할 때 나는 묵직한 기계음 소리
	SET_PROTOCOL(EFFECT_CATAPULTMOVE	)
	// 충차 이동시		충차가 이동할 때 나는 묵직한 기계음 소리
	SET_PROTOCOL(EFFECT_WALLBREAKERMOVE	)
	// 공성 유니트 변신 소리		유저가 공성 유니트로 변신 할 때 나는 소리
	SET_PROTOCOL(EFFECT_UNITCHANGE	)
	// 공성 유니트 전멸 시	위와 상동	모든 공성 유니트는 죽는 것이 아니라 다시 유저의 모습으로 돌아가므로 변신시와 동일하게 적절한 마법적 효과음이 필요
	SET_PROTOCOL(EFFECT_UNITDEAD	)
	// 병력 충원시	그림 제작중	소모된 부대를 충원할 떄 나는 소리
	SET_PROTOCOL(EFFECT_SUPPLEMENT	)
	// 치명적 공격		크리티컬 공격이 발동했을 때 나는 소리
	SET_PROTOCOL(EFFECT_CRITICAL	)	// 900
	// 견고한 방어		견고한 방어가 발동했을 떄 나는 소리
	SET_PROTOCOL(EFFECT_DEFENCE	)

// EOF
#undef	SET_PROTOCOL
}
#endif
