#ifndef _MUSIC_H
#define _MUSIC_H

#ifdef _USE_HASHCODE_EFFECTSOUND
#include <MyHashTable.h> // sagolboss (2004/08/16 14:11) : Hash Table 클래스 추가
#endif

#include <Singleton.h>   // sagolboss (2004/08/16 14:11) : Singleton 클래스 추가
typedef enum	ENUM_EFFECT_TYPE
{						
	EFFECT_INVALID					= -1	,	//	에러값이다.(이 값은 죽어도 절대불변!!!)
	EFFECT_FIRST					= 0		,	//	안쓰는 값. 기준으로 쓰기 위한 값이다.
	EFFECT_NONE						= 0		,	//	세팅값. 이 값을 설정에서 쓰면 작동을 안하게끔 한다.

	EFFECT_ARROW					= 1		,
	EFFECT_ARROWHIT							,
	EFFECT_SWORD							,
	EFFECT_BIGSWORD							,
	EFFECT_GUN								,
	EFFECT_SCREAM							,
	EFFECT_CANNON							,
	EFFECT_CANNONEXP						,
	EFFECT_HORSEDIE							,
	EFFECT_HEAL								,	// 10

	EFFECT_SAM								,
	EFFECT_TANK								,
	EFFECT_CLICK							,
	EFFECT_TITLEBUTTON						,
	EFFECT_BUDA								,
	EFFECT_THUNDER							,
	EFFECT_BULL								,
	EFFECT_FLAME							,
	EFFECT_BOMB								,
	EFFECT_FIRE								,	// 20

	EFFECT_ELECTRIC							,
	EFFECT_SINK								,
	EFFECT_SHIPCANNON						,
	EFFECT_SHIPCANNONDOUBLE					,
	EFFECT_FARMERJDIE						,
	EFFECT_AIRPLANEDIE						,
	EFFECT_CROP								,
	EFFECT_TREE								,
	EFFECT_SMALLCANNON						,
	EFFECT_HALFEXP							,	// 30

	EFFECT_FARMERJWORK						,
	EFFECT_EARTHQUAKE						,
	EFFECT_SAMC								,
	EFFECT_MESSAGE							,
	EFFECT_SHALLOW							,
	EFFECT_DECIDEBUILD						,
	EFFECT_GENERAL4KATTACK					,
	EFFECT_NINJAJ							,
	EFFECT_REPAIRBUILD						,
	EFFECT_RIDEIN							,	// 40

	EFFECT_RIDEOUT							,
	EFFECT_WARP								,
	EFFECT_CANNON2CFIRE						,
	EFFECT_ARROWEXP							,
	EFFECT_SELECTCOUNTRY					,
	EFFECT_TEAM0							,
	EFFECT_TEAM1							,
	EFFECT_TEAM2							,
	EFFECT_TEAM3							,
	EFFECT_TEAM4							,	// 50

	EFFECT_TEAM5							,
	EFFECT_TEAM6							,
	EFFECT_TEAM7							,
	EFFECT_TEAM8							,
	EFFECT_TEAM9							,
	EFFECT_FIRETANKKHIT						,
	EFFECT_CANNONJ							,
	EFFECT_NINJA2JATTACK					,
	EFFECT_NINJA2JHIT						,
	EFFECT_JUSTICEK							,	// 60

	EFFECT_SPEAR2							,
	EFFECT_SPECIALGUN						,
	EFFECT_ITEMON							,
	EFFECT_ITEMOFF							,
	EFFECT_EXTINGUISH						,
	EFFECT_GETITEM							,
	EFFECT_EXP								,
	EFFECT_CANNON2KFIRE						,
	EFFECT_BUILD							,
	EFFECT_GENERAL4KMAGIC					,	// 70

	EFFECT_MAP1								,
	EFFECT_MAP2								,
	EFFECT_NIGHT							,
	EFFECT_DAY								,
	EFFECT_LEVELUP							,
	EFFECT_RAIN								,
	EFFECT_SNOW								,
	EFFECT_DROP								,
	EFFECT_EVENT							,
	EFFECT_STARTGAME						,	// 80

	EFFECT_KIMBOMB							,
	EFFECT_AIRMAGIC							,
	EFFECT_TORNADO							,
	EFFECT_MAGIC8J							,
	EFFECT_MAGIC4C							,	// 기공신포(발사)
	EFFECT_MAGIC4EXP						,	// 기공신포(폭발)
	EFFECT_MAGIC6C							,
	EFFECT_USEITEM							,
	EFFECT_CARTOBUILD						,
	EFFECT_CLUB								,	// 90

	EFFECT_MANAGERWARNING					,
	EFFECT_DROPSTONE						,
	EFFECT_DROPWATER						,
	EFFECT_SNOWWOMANMAGIC					,
	EFFECT_GOLDDRAGONFIRE					,
	EFFECT_SEAKINGFIRE						,
	EFFECT_HORSESWORDJATTACK				,
	EFFECT_BUILDDONE						,
	EFFECT_UPGRADEDONE						,
	EFFECT_CANNOTMAKETHERE					,	// 100

	EFFECT_SAVEDONE							,
	EFFECT_CAPTUREENEMYBUILDMESSAGE			,
	EFFECT_CAPTUREDBUILDMESSAGE				,
	EFFECT_LEVELUPMESSAGE					,
	EFFECT_LEVELDOWNMESSAGE					,
	EFFECT_STEALTECHMESSAGE					,
	EFFECT_STOLENTECHMESSAGE				,
	EFFECT_BEATTACKEDMESSAGE				,
	EFFECT_TRAINSPOTDONEMESSAGE				,
	EFFECT_MINEEXPLODEMESSAGE				,	// 110

	EFFECT_WAIT_KW							,
	EFFECT_MOVE_KW							,
	EFFECT_HUNGRY_KW0						,
	EFFECT_HUNGRY_KW1						,
	EFFECT_HUNGRY_KW2						,
	EFFECT_EAT_KW0							,
	EFFECT_EAT_KW1							,
	EFFECT_EAT_KW2							,
	EFFECT_SELECT_KW						,
	EFFECT_ATTACK_KW						,	// 120

	EFFECT_DIE_KW							,
	EFFECT_WAIT_JW							,
	EFFECT_MOVE_JW							,
	EFFECT_HUNGRY_JW0						,
	EFFECT_HUNGRY_JW1						,
	EFFECT_HUNGRY_JW2						,
	EFFECT_EAT_JW0							,
	EFFECT_EAT_JW1							,
	EFFECT_EAT_JW2							,
	EFFECT_SELECT_JW						,	// 130

	EFFECT_ATTACK_JW						,
	EFFECT_DIE_JW							,
	EFFECT_WAIT_KM							,
	EFFECT_MOVE_KM							,
	EFFECT_HUNGRY_KM0						,
	EFFECT_HUNGRY_KM1						,
	EFFECT_HUNGRY_KM2						,
	EFFECT_EAT_KM0							,
	EFFECT_EAT_KM1							,
	EFFECT_EAT_KM2							,	// 140

	EFFECT_SELECT_KM						,
	EFFECT_ATTACK_KM						,
	EFFECT_DIE_KM							,
	EFFECT_WAIT_JM							,
	EFFECT_MOVE_JM							,
	EFFECT_HUNGRY_JM0						,
	EFFECT_HUNGRY_JM1						,
	EFFECT_HUNGRY_JM2						,
	EFFECT_EAT_JM0							,
	EFFECT_EAT_JM1							,	// 150

	EFFECT_EAT_JM2							,
	EFFECT_SELECT_JM						,
	EFFECT_ATTACK_JM						,
	EFFECT_DIE_JM							,
	EFFECT_WAIT_TM							,
	EFFECT_MOVE_TM							,
	EFFECT_HUNGRY_TM0						,
	EFFECT_HUNGRY_TM1						,
	EFFECT_HUNGRY_TM2						,
	EFFECT_EAT_TM0							,	// 160

	EFFECT_EAT_TM1							,
	EFFECT_EAT_TM2							,
	EFFECT_SELECT_TM						,
	EFFECT_ATTACK_TM						,
	EFFECT_DIE_TM							,
	EFFECT_WAIT_TW							,
	EFFECT_MOVE_TW							,
	EFFECT_HUNGRY_TW0						,
	EFFECT_HUNGRY_TW1						,
	EFFECT_HUNGRY_TW2						,	// 170

	EFFECT_EAT_TW0							,
	EFFECT_EAT_TW1							,
	EFFECT_EAT_TW2							,
	EFFECT_SELECT_TW						,
	EFFECT_ATTACK_TW						,
	EFFECT_DIE_TW							,
	EFFECT_WAIT_CM							,	// 중국 남자
	EFFECT_MOVE_CM							,
	EFFECT_HUNGRY_CM0						,
	EFFECT_HUNGRY_CM1						,	// 180

	EFFECT_HUNGRY_CM2						,
	EFFECT_EAT_CM0							,
	EFFECT_EAT_CM1							,
	EFFECT_EAT_CM2							,
	EFFECT_SELECT_CM						,
	EFFECT_ATTACK_CM						,
	EFFECT_DIE_CM							,
	EFFECT_WAIT_CW							,	// 중국 여자
	EFFECT_MOVE_CW							,
	EFFECT_HUNGRY_CW0						,	// 190

	EFFECT_HUNGRY_CW1						,
	EFFECT_HUNGRY_CW2						,
	EFFECT_EAT_CW0							,
	EFFECT_EAT_CW1							,
	EFFECT_EAT_CW2							,
	EFFECT_SELECT_CW						,
	EFFECT_ATTACK_CW						,
	EFFECT_DIE_CW							,
	EFFECT_SELECT_FARMERK					,	// 병사 유닛 선택
	EFFECT_SELECT_FARMERC					,	// 200

	EFFECT_SELECT_SWORDC					,
	EFFECT_SELECT_BUDAC						,
	EFFECT_SELECT_GUNC						,
	EFFECT_SELECT_HEAVYGUNC					,
	EFFECT_SELECT_MECH						,
	EFFECT_SELECT_ATTACKERC					,
	EFFECT_SELECT_GENERALK1					,
	EFFECT_SELECT_GENERALK2					,
	EFFECT_SELECT_GENERALK3					,
	EFFECT_SELECT_GENERALK4					,	// 210

	EFFECT_SELECT_GENERALK5					,
	EFFECT_SELECT_GENERALK6					,
	EFFECT_SELECT_GENERALK7					,
	EFFECT_SELECT_GENERALK8					,
	EFFECT_SELECT_GENERALJ1					,
	EFFECT_SELECT_GENERALJ2					,
	EFFECT_SELECT_GENERALJ3					,
	EFFECT_SELECT_GENERALJ4					,
	EFFECT_SELECT_GENERALJ5					,
	EFFECT_SELECT_GENERALJ6					,	// 220

	EFFECT_SELECT_GENERALJ7					,
	EFFECT_SELECT_GENERALJ8					,
	EFFECT_SELECT_GENERAL_C1				,
	EFFECT_SELECT_GENERAL_C3				,
	EFFECT_SELECT_GENERAL_C4				,
	EFFECT_SELECT_GENERAL_C5				,
	EFFECT_DIE_FARMERK						,
	EFFECT_DIE_FARMERC						,
	EFFECT_DIE_SWORDC						,
	EFFECT_DIE_BUDAC						,	// 230

	EFFECT_DIE_GUNC							,
	EFFECT_DIE_HEAVYGUNC					,
	EFFECT_DIE_ATTACKERC					,
	EFFECT_DIE_EAGLEC						,
	EFFECT_MOVE_FARMERK						,
	EFFECT_MOVE_FARMERC						,
	EFFECT_MOVE_SWORDC						,
	EFFECT_MOVE_GUNC						,
	EFFECT_MOVE_HEAVYGUNC					,
	EFFECT_MOVE_BUDAC						,	// 240

	EFFECT_MOVE_GENERALK1					,
	EFFECT_MOVE_GENERALK2					,
	EFFECT_MOVE_GENERALK3					,
	EFFECT_MOVE_GENERALK4					,
	EFFECT_MOVE_GENERALK5					,
	EFFECT_MOVE_GENERALK6					,
	EFFECT_MOVE_GENERALK7					,
	EFFECT_MOVE_GENERALK8					,
	EFFECT_MOVE_GENERALJ1					,
	EFFECT_MOVE_GENERALJ2					,	// 250

	EFFECT_MOVE_GENERALJ3					,
	EFFECT_MOVE_GENERALJ4					,
	EFFECT_MOVE_GENERALJ5					,
	EFFECT_MOVE_GENERALJ6					,
	EFFECT_MOVE_GENERALJ7					,
	EFFECT_MOVE_GENERALJ8					,
	EFFECT_MOVE_GENERAL_C1					,
	EFFECT_MOVE_GENERAL_C3					,
	EFFECT_MOVE_GENERAL_C4					,
	EFFECT_MOVE_GENERAL_C5					,	// 260

	EFFECT_MOVE_SHIP						,
	EFFECT_MOVE_CANNON2K					,
	EFFECT_MOVE_EAGLEC						,
	EFFECT_MOVE_CANNONJ						,
	EFFECT_MOVE_ATTACKERJ					,
	EFFECT_ATTACK_FARMERK					,
	EFFECT_ATTACK_FARMERC					,
	EFFECT_ATTACK_SWORDC					,
	EFFECT_ATTACK_GUNC						,
	EFFECT_ATTACK_HEAVYGUNC					,	// 270

	EFFECT_ATTACK_BUDAC						,
	EFFECT_ATTACK_GENERALK1					,
	EFFECT_ATTACK_GENERALK2					,
	EFFECT_ATTACK_GENERALK3					,
	EFFECT_ATTACK_GENERALK4					,
	EFFECT_ATTACK_GENERALK5					,
	EFFECT_ATTACK_GENERALK6					,
	EFFECT_ATTACK_GENERALK7					,
	EFFECT_ATTACK_GENERALK8					,
	EFFECT_ATTACK_GENERALJ1					,	// 280

	EFFECT_ATTACK_GENERALJ2					,
	EFFECT_ATTACK_GENERALJ3					,
	EFFECT_ATTACK_GENERALJ4					,
	EFFECT_ATTACK_GENERALJ5					,
	EFFECT_ATTACK_GENERALJ6					,
	EFFECT_ATTACK_GENERALJ7					,
	EFFECT_ATTACK_GENERALJ8					,
	EFFECT_ATTACK_GENERAL_C1				,
	EFFECT_ATTACK_GENERAL_C3				,
	EFFECT_ATTACK_GENERAL_C4				,	// 290

	EFFECT_ATTACK_GENERAL_C5				,
	EFFECT_ON_ATTACK_WEIRDPLANT				,
	EFFECT_ON_DIE_WEIRDPLANT				,
	EFFECT_ON_DIE_STARFISH					,
	EFFECT_ON_ITEMONOFF						,
	EFFECT_ON_DIE_TIGER						,
	EFFECT_ON_DIE_FURHEADDEMON				,
	EFFECT_ON_DIE_DEER						,
	EFFECT_ON_DIE_BAT						,
	EFFECT_ON_DIE_GACKDAGUI					,	// 300

	EFFECT_ON_DIE_GATPHA					,
	EFFECT_ON_DIE_DOGDEMON					,
	EFFECT_ON_DIE_DUEOKSINI					,
	EFFECT_ON_DIE_RACCOONDOG				,
	EFFECT_ON_DIE_HUNGRYDEMON				,
	EFFECT_ON_DIE_EATERDEMON				,
	EFFECT_ON_DIE_ONI						,
	EFFECT_ON_DIE_GOLDDRAGON				,
	EFFECT_ON_DIE_FIREDRAGON				,
	EFFECT_ON_DIE_SNOWDEMON					,	// 310

	EFFECT_ON_DIE_TOAD						,
	EFFECT_ON_DIE_CENTIPEDE					,
	EFFECT_ON_DIE_BANDIT1					,
	EFFECT_ON_DIE_BANDIT2					,
	EFFECT_ON_DIE_BANDIT3					,
	EFFECT_ON_DIE_BANDIT4					,
	EFFECT_ON_DIE_SWORDPIRATE				,
	EFFECT_SELECT_ONGHWA					,	// 온천원숭이
	EFFECT_MOVE_ONGHWA						,
	EFFECT_ATTACK_ONGHWA					,	// 320

	EFFECT_DIE_ONGHWA						,
	EFFECT_SELECT_BANDIT1					,	// 꼬마산적
	EFFECT_SELECT_PORTERK					,	// 조선짐꾼
	EFFECT_MOVE_PORTERK						,
	EFFECT_DIE_PORTERK						,
	EFFECT_SELECT_SWORDK					,	// 창잡이
	EFFECT_MOVE_SWORDK						,
	EFFECT_ATTACK_SWORDK					,
	EFFECT_DIE_SWORDK						,
	EFFECT_SELECT_ARCHERK					,	// 330 활잡이

	EFFECT_MOVE_ARCHERK						,
	EFFECT_ATTACK_ARCHERK					,
	EFFECT_DIE_ARCHERK						,
	EFFECT_SELECT_BUDAK						,	// 파계승
	EFFECT_MOVE_BUDAK						,
	EFFECT_ATTACK_BUDAK						,
	EFFECT_DIE_BUDAK						,
	EFFECT_SELECT_HORSEARCHERK				,	// 기마궁수
	EFFECT_MOVE_HORSEARCHERK				,
	EFFECT_ATTACK_HORSEARCHERK				,	// 340

	EFFECT_DIE_HORSEARCHERK					,
	EFFECT_SELECT_JUSTICEK					,	// 유생
	EFFECT_MOVE_JUSTICEK					,
	EFFECT_ATTACK_JUSTICEK					,
	EFFECT_DIE_JUSTICEK						,
	EFFECT_SELECT_ADVBUDAJ					,	// 퇴마사
	EFFECT_MOVE_ADVBUDAJ					,
	EFFECT_ATTACK_ADVBUDAJ					,
	EFFECT_DIE_ADVBUDAJ						,
	EFFECT_SELECT_FARMERJ					,	// 350 일본 짐꾼

	EFFECT_MOVE_FARMERJ						,
	EFFECT_DIE_FARMERJ						,
	EFFECT_SELECT_SWORDJ					,	// 검술낭인
	EFFECT_MOVE_SWORDJ						,
	EFFECT_ATTACK_SWORDJ					,
	EFFECT_DIE_SWORDJ						,
	EFFECT_SELECT_GUNJ						,	// 조총낭인
	EFFECT_MOVE_GUNJ						,
	EFFECT_ATTACK_GUNJ						,
	EFFECT_DIE_GUNJ							,	// 360

	EFFECT_SELECT_HORSESWORDJ				,	// 늑대낭인
	EFFECT_MOVE_HORSESWORDJ					,
	EFFECT_ATTACK_HORSESWORDJ				,
	EFFECT_DIE_HORSESWORDJ					,
	EFFECT_SELECT_ELEPHANT					,	// 눈코끼리
	EFFECT_ATTACK_ELEPHANT					,
	EFFECT_DIE_ELEPHANT						,
	EFFECT_DIE_SEAKING						,	// 해저왕
	EFFECT_DIE_BEAR							,	// 반달곰
	EFFECT_SELECT_BEAR						,	// 370

	EFFECT_ATTACK_BEAR						,
	EFFECT_HOSPITAL00						,	// 의원
	EFFECT_HOSPITAL10						,
	EFFECT_HOSPITAL20						,
	EFFECT_HOSPITAL30						,
	EFFECT_HOSPITAL40						,
	EFFECT_BARRACK00						,	// 훈련소
	EFFECT_BARRACK10						,
	EFFECT_GOV00							,	// 관청
	EFFECT_GOV10							,	// 380

	EFFECT_GOV00T							,	
	EFFECT_GOV10T							,
	EFFECT_USEITEM_POTION					,
	EFFECT_USEITEM_FRUIT					,
	EFFECT_USEITEM_SWORD					,
	EFFECT_USEITEM_HELMET					,
	EFFECT_USEITEM_MEET						,
	EFFECT_USEITEM_CLOTH					,
	EFFECT_USEITEM_ARMOUR					,
	EFFECT_USEITEM_WEAPON					,	// 390

	EFFECT_ON_GET_ITEM						,
	EFFECT_ON_DROP_ITEM						,
	EFFECT_ON_HEAL							,
	EFFECT_ON_DISMISS						,
	EFFECT_CANNOTENTERVILLAGE				,
	EFFECT_ITEMEQUIP0						,
	EFFECT_STARTBATTLE						,
	EFFECT_COUNTDOWN						,
	EFFECT_SETBATTLEMODE					,
	EFFECT_ONGHWAATTACK						,	// 400

	EFFECT_BUILD_WEAPONSHOP					,
	EFFECT_CLON								,
	EFFECT_FIRE_JUSTICEK					,
	EFFECT_ICEPALSY							,
	EFFECT_QUEST_ASIGN						,
	EFFECT_QUEST_CLEAR						,
	EFFECT_TUTTLEWAVE						,
	EFFECT_SELECT_SEAHORSE					,	// 해마
	EFFECT_DIE_SEAHORSE						,
	EFFECT_SELECT_CAT						,	// 410 도둑고양이

	EFFECT_DIE_CAT							,
	EFFECT_FIRE_CAT							,
	EFFECT_SELECT_DUCK						,	// 대만오리
	EFFECT_DIE_DUCK							,
	EFFECT_FIRE_DUCK						,
	EFFECT_SELECT_HORNET					,	// 왕벌
	EFFECT_DIE_HORNET						,
	EFFECT_SELECT_SWORDPIRATE				,	// 왜구
	EFFECT_ATTACK_SWORDPIRATE				,
	EFFECT_SELECT_GUNPIRATE					,	// 420 조총왜구

	EFFECT_ATTACK_GUNPIRATE					,
	EFFECT_SELECT_ONI						,	// 오니
	EFFECT_ATTACK_ONI						,
	EFFECT_SELECT_SNOWWOMAN					,	// 설녀
	EFFECT_ATTACK_SNOWWOMAN					,
	EFFECT_MINIGAME1_START					,	// 미니게임
	EFFECT_MINIGAME1_TIME					,
	EFFECT_MINIGAME1_CARD					,
	EFFECT_MINIGAME1_CARDCOVER				,
	EFFECT_MINIGAME1_PAIR					,	// 430

	EFFECT_MINIGAME3_FRUITOK				,
	EFFECT_MINIGAME3_FRUITFAIL				,
	EFFECT_GETCASTLE						,	// 성함락
	EFFECT_ON_DIE_BOGY						,	// 도깨비
	EFFECT_TRY_BOGY							,
	EFFECT_ON_DIE_SNOWWOMAN					,	// 설녀
	EFFECT_TRY_SNOWWOMAN					,
	EFFECT_ON_DIE_FOX						,	// 구미호
	EFFECT_TRY_FOX							,
	EFFECT_SELECT_NINJAJ					,	// 440 닌자

	EFFECT_MOVE_NINJAJ						,
	EFFECT_ATTACK_NINJAJ					,
	EFFECT_DIE_NINJAJ						,
	EFFECT_SELECT_CHAWOO					,	// 차우차우
	EFFECT_ATTACK_CHAWOO					,
	EFFECT_DIE_CHAWOO						,
	EFFECT_SELECT_WILDBOAR					,	// 멧돼지
	EFFECT_ATTACK_WILDBOAR					,
	EFFECT_DIE_WILDBOAR						,
	EFFECT_SELECT_GANGSI					,	// 450 강시

	EFFECT_ATTACK_GANGSI					,
	EFFECT_DIE_GANGSI						,
	EFFECT_SELECT_BABARIAN					,	// 원주민
	EFFECT_SELECT_BSHAMAN					,	// 원주민무당
	EFFECT_SELECT_NPC_HONG					,	// NPC 홍글동
	EFFECT_SELECT_GENERAL1T					,	// 왕거한
	EFFECT_MOVE_GENERAL1T					,
	EFFECT_ATTACK_GENERAL1T					,
	EFFECT_DIE_GENERAL1T					,
	EFFECT_SELECT_GENERAL4T					,	// 460 유영복

	EFFECT_MOVE_GENERAL4T					,
	EFFECT_ATTACK_GENERAL4T					,
	EFFECT_DIE_GENERAL4T					,
	EFFECT_SELECT_PORTERT					,	// 대만짐꾼
	EFFECT_MOVE_PORTERT						,
	EFFECT_ATTACK_PORTERT					,
	EFFECT_DIE_PORTERT						,
	EFFECT_SELECT_AXET						,	// 도끼거한
	EFFECT_MOVE_AXET						,
	EFFECT_ATTACK_AXET						,	// 470

	EFFECT_DIE_AXET							,
	EFFECT_SELECT_GUNT						,	// 서양총수
	EFFECT_MOVE_GUNT						,
	EFFECT_ATTACK_GUNT						,
	EFFECT_DIE_GUNT							,
	EFFECT_SELECT_BUDAT						,	// 주술사
	EFFECT_MOVE_BUDAT						,
	EFFECT_ATTACK_BUDAT						,
	EFFECT_DIE_BUDAT						,
	EFFECT_SELECT_SWORDT					,	// 480 봉술가

	EFFECT_MOVE_SWORDT						,
	EFFECT_ATTACK_SWORDT					,
	EFFECT_DIE_SWORDT						,
	EFFECT_SELECT_GENERAL2T					,	// 페르난데스
	EFFECT_MOVE_GENERAL2T					,
	EFFECT_ATTACK_GENERAL2T					,
	EFFECT_DIE_GENERAL2T					,
	EFFECT_SELECT_GENERAL3T					,	// 임평후
	EFFECT_MOVE_GENERAL3T					,
	EFFECT_ATTACK_GENERAL3T					,	// 490

	EFFECT_DIE_GENERAL3T					,
	EFFECT_SELECT_AMAZONT					,	// 여전사
	EFFECT_MOVE_AMAZONT						,
	EFFECT_ATTACK_AMAZONT					,
	EFFECT_DIE_AMAZONT						,
	EFFECT_SELECT_GENERAL5T					,	// 조세림
	EFFECT_MOVE_GENERAL5T					,
	EFFECT_ATTACK_GENERAL5T					,
	EFFECT_DIE_GENERAL5T					,
	EFFECT_HOSPITAL00T						,	// 500 대만의원

	EFFECT_HOSPITAL10T						,
	EFFECT_HOSPITAL20T						,
	EFFECT_HOSPITAL30T						,
	EFFECT_HOSPITAL40T						,
	EFFECT_SELECT_FANC						,	// 모험가
	EFFECT_MOVE_FANC						,
	EFFECT_ATTACK_FANC						,
	EFFECT_DIE_FANC							,
	EFFECT_SELECT_PORTERC					,	// 중국짐꾼
	EFFECT_MOVE_PORTERC						,	// 510

	EFFECT_DIE_PORTERC						,
	EFFECT_SELECT_MUDOGAC					,	// 무도가
	EFFECT_MOVE_MUDOGAC						,
	EFFECT_ATTACK_MUDOGAC					,
	EFFECT_DIE_MUDOGAC						,
	EFFECT_SELECT_BUDAKC					,	// 수도승
	EFFECT_MOVE_BUDAKC						,
	EFFECT_ATTACK_BUDAKC					,
	EFFECT_DIE_BUDAKC						,
	EFFECT_SELECT_BIGSWORDC					,	// 520 큰칼무사

	EFFECT_MOVE_BIGSWORDC					,
	EFFECT_ATTACK_BIGSWORDC					,
	EFFECT_DIE_BIGSWORDC					,
	EFFECT_SELECT_FIREGUNC					,	// 화포수
	EFFECT_MOVE_FIREGUNC					,
	EFFECT_ATTACK_FIREGUNC					,
	EFFECT_DIE_FIREGUNC						,
	EFFECT_DIE_GENERAL_C1					,	// 중국장수사망
	EFFECT_DIE_GENERAL_C3					,
	EFFECT_DIE_GENERAL_C4					,	// 530

	EFFECT_DIE_GENERAL_C5					,
	EFFECT_DIE_GENERALJ2					,	// 일본장수사망(가토)
	EFFECT_DIE_GENERALJ3					,	// 와키자카
	EFFECT_DIE_GENERALJ4					,	// 세이쇼오
	EFFECT_DIE_GENERALJ6					,	// 도쿠가와
	EFFECT_DIE_GENERALJ8					,	// 아사코
	EFFECT_SELECT_SMALLGANG					,	// 졸개마적
	EFFECT_SELECT_MBANDIT3					,	// 총수마적
	EFFECT_ATTACK_MBANDIT3					,
	EFFECT_SELECT_PIRATES					,	// 540 해적

	EFFECT_ATTACK_PIRATES					,
	EFFECT_SELECT_SEAKING					,	// 해저왕
	EFFECT_ATTACK_SEAKING					,
	EFFECT_SELECT_MBANDIT1					,	// 마적두목
	EFFECT_ATTACK_MBANDIT1					,
	EFFECT_HOSPITAL00J						,
	EFFECT_HOSPITAL10J						,
	EFFECT_HOSPITAL20J						,
	EFFECT_HOSPITAL30J						,
	EFFECT_HOSPITAL40J						,	// 550

	EFFECT_GOV00J							,
	EFFECT_GOV10J							,
	EFFECT_BARRACK00J						,
	EFFECT_BARRACK10J						,
	EFFECT_SELECT_BIGTREE					,	// 거대수
	EFFECT_ATTACK_BIGTREE					,
	EFFECT_DIE_BIGTREE						,
	EFFECT_SELECT_CACTUS					,	// 괴물선인장
	EFFECT_ATTACK_CACTUS					,
	EFFECT_DIE_CACTUS						,	// 560

	EFFECT_SELECT_SNAKE						,	// 구렁이
	EFFECT_ATTACK_SNAKE						,
	EFFECT_DIE_SNAKE						,
	EFFECT_SELECT_SCORPION					,	// 독전갈
	EFFECT_ATTACK_SCORPION					,
	EFFECT_DIE_SCORPION						,
	EFFECT_SELECT_HORSEMAN					,	// 마두인
	EFFECT_ATTACK_HORSEMAN					,
	EFFECT_DIE_HORSEMAN						,
	EFFECT_SELECT_SANDGOD					,	// 570 모래의신

	EFFECT_ATTACK_SANDGOD					,
	EFFECT_DIE_SANDGOD						,
	EFFECT_SELECT_SEAENVOY					,	// 바다의사신
	EFFECT_ATTACK_SEAENVOY					,
	EFFECT_DIE_SEAENVOY						,
	EFFECT_SELECT_SNOWDEMON					,	// 설인
	EFFECT_ATTACK_SNOWDEMON					,
	EFFECT_DIE_SNOWDEMON					,
	EFFECT_SELECT_CROCODILE					,	// 식인악어
	EFFECT_ATTACK_CROCODILE					,	// 580

	EFFECT_DIE_CROCODILE					,
	EFFECT_SELECT_LAVAMONSTER				,	// 용암괴물
	EFFECT_ATTACK_LAVAMONSTER				,
	EFFECT_DIE_LAVAMONSTER					,
	EFFECT_SELECT_EVIL						,	// 이사의사념
	EFFECT_ATTACK_EVIL						,
	EFFECT_DIE_EVIL							,
	EFFECT_ATTACK_WEASEL					,	// 족제비
	EFFECT_DIE_WEASEL						,
	EFFECT_SELECT_SOUL						,	// 590 징기스칸의혼

	EFFECT_ATTACK_SOUL						,
	EFFECT_DIE_SOUL							,
	EFFECT_SELECT_COBRA						,	// 코브라
	EFFECT_ATTACK_COBRA						,
	EFFECT_DIE_COBRA						,
	EFFECT_SELECT_PANDA						,	// 팬더
	EFFECT_ATTACK_PANDA						,
	EFFECT_DIE_PANDA						,
	EFFECT_SELECT_VOLCANOFLAME				,	// 화산의불꽃
	EFFECT_ATTACK_VOLCANOFLAME				,	// 600

	EFFECT_DIE_VOLCANOFLAME					,
	EFFECT_SELECT_MADBULL					,	// 광우
	EFFECT_ATTACK_MADBULL					,
	EFFECT_DIE_MADBULL						,	// 인면조
	EFFECT_SELECT_BIRD						,
	EFFECT_ATTACK_BIRD						,
	EFFECT_DIE_BIRD							,	// 처녀귀신
	EFFECT_SELECT_KOREANGHOST				,
	EFFECT_ATTACK_KOREANGHOST				,
	EFFECT_DIE_KOREANGHOST					,	// 610

	EFFECT_SELECT_GACKDAGUI					,	// 각다귀
	EFFECT_ATTACK_GACKDAGUI					,
	EFFECT_SELECT_RUNNERHAND				,	// 괴물덩굴손
	EFFECT_DIE_RUNNERHAND					,
	EFFECT_ATTACK_RUNNERHAND				,
	EFFECT_SELECT_DOGDEMON					,	// 견신
	EFFECT_ATTACK_DOGDEMON					,
	EFFECT_SELECT_GHOSTCAT					,	// 귀묘
	EFFECT_DIE_GHOSTCAT						,
	EFFECT_ATTACK_GHOSTCAT					,	// 620

	EFFECT_ATTACK_RACOONDOG					,	// 너구리
	EFFECT_SELECT_RACOONDOG					,
	EFFECT_ATTACK_SNOWLIZARD				,	// 눈도마뱀
	EFFECT_SELECT_SNOWLIZARD				,
	EFFECT_DIE_SNOWLIZARD					,
	EFFECT_ATTACK_DUCK						,	// 대만오리
	EFFECT_ATTACK_HORNET					,	// 대만왕벌
	EFFECT_ATTACK_CAT						,	// 도둑고양이
	EFFECT_DIE_BUTTERFLY					,	// 독나방
	EFFECT_ATTACK_BUTTERFLY					,	// 630

	EFFECT_SELECT_BUTTERFLY					,
	EFFECT_SELECT_TOAD						,	// 독두꺼비
	EFFECT_DIE_TOAD							,
	EFFECT_ATTACK_TOAD						,
	EFFECT_SELECT_CENTIPEDE					,	// 독지네
	EFFECT_ATTACK_CENTIPEDE					,
	EFFECT_ATTACK_HARUBANG					,	// 돌하루방
	EFFECT_SELECT_HARUBANG					,
	EFFECT_DIE_HARUBANG						,
	EFFECT_ATTACK_DUEOKSINI					,	// 640 두억시니

	EFFECT_SELECT_DUEOKSINI					,
	EFFECT_DIE_DUEOKSINI					,
	EFFECT_SELECT_WORRIORGHOST				,	// 무관의혼
	EFFECT_ATTACK_WORRIORGHOST				,
	EFFECT_DIE_WORRIORGHOST					,
	EFFECT_SELECT_TUTTLE					,	// 바다거북이
	EFFECT_ATTACK_TUTTLE					,
	EFFECT_DIE_TUTTLE						,
	EFFECT_SELECT_CRAB						,	// 바다게
	EFFECT_ATTACK_CRAB						,	// 650

	EFFECT_DIE_CRAB							,
	EFFECT_SELECT_WIDOW						,	// 거미요괴
	EFFECT_ATTACK_WIDOW						,
	EFFECT_DIE_WIDOW						,
	EFFECT_ATTACK_BAT						,	// 박쥐
	EFFECT_SELECT_BAT						,
	EFFECT_SELECT_WHITETIGER				,	// 백호
	EFFECT_ATTACK_WHITETIGER				,
	EFFECT_DIE_WHITETIGER					,
	EFFECT_SELECT_STARFISH					,	// 660 불가사리

	EFFECT_ATTACK_STARFISH					,
	EFFECT_SELECT_INSECT					,	// 사마귀
	EFFECT_ATTACK_INSECT					,
	EFFECT_DIE_INSECT						,
	EFFECT_SELECT_DEER						,	// 사슴
	EFFECT_ATTACK_DEER						,
	EFFECT_SELECT_VIPER						,	// 살모사
	EFFECT_ATTACK_VIPER						,
	EFFECT_DIE_VIPER						,
	EFFECT_DIE_SNOWWOMAN					,	// 670 설녀

	EFFECT_ATTACK_EATERDEMON				,	// 식귀
	EFFECT_SELECT_EATERDEMON				,
	EFFECT_ATTACK_SINGERMGHOST				,	// 신검의혼
	EFFECT_SELECT_SINGERMGHOST				,
	EFFECT_DIE_SINGERMGHOST					,
	EFFECT_ATTACK_HUNGRYDEMON				,	// 아귀
	EFFECT_SELECT_HUNGRYDEMON				,
	EFFECT_DIE_HUNGRYDEMON					,
	EFFECT_ATTACK_ICETREE					,	// 얼음나무
	EFFECT_SELECT_ICETREE					,	// 680

	EFFECT_DIE_ICETREE						,
	EFFECT_DIE_ONI							,	// 오니
	EFFECT_ATTACK_LEECH						,	// 왕거머리
	EFFECT_SELECT_LEECH						,
	EFFECT_DIE_LEECH						,
	EFFECT_ATTACK_MAGICIAN					,	// 요술사
	EFFECT_SELECT_MAGICIAN					,
	EFFECT_DIE_MAGICIAN						,
	EFFECT_ATTACK_BABARIANSHAMAN			,	// 원주민무당
	EFFECT_SELECT_BABARIANSHAMAN			,	// 690

	EFFECT_DIE_BABARIANSHAMAN				,
	EFFECT_ATTACK_SMALLGANG					,	// 졸개마적
	EFFECT_DIE_SMALLGANG					,
	EFFECT_ATTACK_FURHEADDEMON				,	// 털가면
	EFFECT_SELECT_FURHEADDEMON				,
	EFFECT_ATTACK_TIGER						,	// 호랑이
	EFFECT_SELECT_TIGER						,
	EFFECT_DIE_TIGER						,
	EFFECT_ATTACK_FIREDRAGON				,	// 화룡
	EFFECT_SELECT_FIREDRAGON				,	// 700

	EFFECT_ATTACK_GOLDDRAGON				,	// 황룡
	EFFECT_SELECT_GOLDDRAGON				,
	EFFECT_DIE_PIRATES						,	// 해적
	EFFECT_ATTACK_SEAHORSE					,	// 해마
	EFFECT_ATTACK_BANDIT1					,	// 꼬마산적
	EFFECT_DIE_SWORDPIRATE					,	// 왜구
	EFFECT_DIE_BABARIAN						,	// 원주민
	EFFECT_DIE_MBANDIT3						,	// 총수마적
	EFFECT_SELECT_WEASEL					,	// 족제비
	EFFECT_DIE_GUNPIRATE					,	// 710 조총왜구

	EFFECT_ATTACK_HOOK						,	// 갈고리해적
	EFFECT_DIE_HOOK							,
	EFFECT_ATTACK_SKYNINE					,	// 천구
	EFFECT_DIE_SKYNINE						,
	EFFECT_ATTACK_HORSESPEAR				,	// 기마창수
	EFFECT_DIE_HORSESPEAR					,
	EFFECT_ATTACK_THIEF						,	// 도굴꾼
	EFFECT_DIE_THIEF						,
	EFFECT_ATTACK_MBANDIT2					,	// 망치마적
	EFFECT_DIE_MBANDIT2						,	// 720

	EFFECT_ATTACK_AMAKUSA					,	// 아마쿠사
	EFFECT_DIE_AMAKUSA						,
	EFFECT_ATTACK_BADMERCHANT				,	// 악덕상인
	EFFECT_DIE_BADMERCHANT					,
	EFFECT_ATTACK_BOGY						,	// 도깨비
	EFFECT_ATTACK_BANDIT2					,	// 산적
	EFFECT_ATTACK_BANDIT3					,	// 철퇴산적
	EFFECT_ATTACK_FOX						,	// 구미호
	EFFECT_ATTACK_GATPHA					,	// 갓파
	EFFECT_ATTACK_GENERAL_C1_EXT			,	// 730 동방불패

	EFFECT_ATTACK_GENERAL_C2_EXT			,	// 이령
	EFFECT_ATTACK_GENERAL_C3_EXT			,	// 제갈공명
	EFFECT_ATTACK_GENERAL_C4_EXT			,	// 조승훈
	EFFECT_ATTACK_GENERAL_C5_EXT			,	// 축융
	EFFECT_ATTACK_GENERAL_T1_EXT			,	// 왕거한
	EFFECT_ATTACK_GENERAL_T2_EXT			,	// 페르난데스
	EFFECT_ATTACK_GENERAL_T3_EXT			,	// 임평후
	EFFECT_ATTACK_GENERAL_T4_EXT			,	// 유영복
	EFFECT_ATTACK_GENERAL_T5_EXT			,	// 조세림
	EFFECT_ATTACK_GENERAL_J6_EXT			,	// 740 도쿠가와

	EFFECT_ATTACK_GENERAL_J4_EXT			,	// 세이쇼
	EFFECT_ATTACK_GENERAL_J8_EXT			,	// 아사코
	EFFECT_ATTACK_GENERAL_K8_EXT			,	// 김시민
	EFFECT_ATTACK_GENERAL_K8_EXT2			,
	EFFECT_ATTACK_GENERAL_K3_EXT			,	// 유성룡
	EFFECT_ATTACK_GENERAL_K2_EXT			,	// 이순신
	EFFECT_ATTACK_GENERAL_K5_EXT			,	// 신립
	EFFECT_SELECT_SKYNINE					,	// 천구
	EFFECT_SELECT_AMAKUSA					,	// 아마쿠사
	EFFECT_SELECT_HOOK						,	// 750

	EFFECT_DIE_GENERALK5					,	// 신립
	EFFECT_DIE_GENERALK2					,	// 이순신
	EFFECT_DIE_GENERALK8					,	// 김시민
	EFFECT_DIE_GENERALK4					,	// 사명대사
	EFFECT_DIE_GENERALK3					,	// 유성룡
	EFFECT_ARMOR_CLOTH						,
	EFFECT_ARMOR_METAL						,
	EFFECT_ARMOR_RARE						,
	EFFECT_ARMOR_WOODEN						,
	EFFECT_BELT_CLOTH						,	// 760

	EFFECT_BELT_METAL						,
	EFFECT_BELT_RARE						,
	EFFECT_GLOVE_CLOTH						,
	EFFECT_GLOVE_METAL						,
	EFFECT_GLOVE_RARE						,
	EFFECT_GLOVE_WOODEN						,
	EFFECT_HELMET_CLOTH						,
	EFFECT_HELMET_METAL						,
	EFFECT_HELMET_RARE						,
	EFFECT_HELMET_WOODEN					,	// 770

	EFFECT_HELMET_HAT						,
	EFFECT_SHOES_CLOTH						,
	EFFECT_SHOES_ETC						,
	EFFECT_SHOES_METAL						,
	EFFECT_SHOES_WOODEN						,
	EFFECT_WEAPON_DART						,
	EFFECT_WEAPON_GUN						,
	EFFECT_WEAPON_ARROW						,
	EFFECT_WEAPON_RING						,
	EFFECT_WEAPON_SWORD						,	// 780

	EFFECT_WEAPON_WOODEN					,
	EFFECT_ETC								,
	EFFECT_ATTACK_TIRANO					,	// 티라노
	EFFECT_DIE_TIRANO						,
	EFFECT_ATTACK_RAPTOR					,	// 랩터
	EFFECT_DIE_RAPTOR						,
	EFFECT_ATTACK_FLYDRAGON					,	// 익룡
	EFFECT_DIE_FLYDRAGON					,
	EFFECT_ATTACK_CLAYFIGURE				,	// 기마병마용
	EFFECT_DIE_CLAYFIGURE					,	// 790

	EFFECT_SELECT_CLAYFIGURE				,
	EFFECT_ATTACK_GATEKEEPER				,	// 문지기
	EFFECT_DIE_GATEKEEPER					,
	EFFECT_SELECT_GATEKEEPER				,
	EFFECT_ATTACK_PHOENIX					,	// 불사조
	EFFECT_DIE_PHOENIX						,
	EFFECT_SELECT_PHOENIX					,
	EFFECT_ATTACK_HELLKING					,	// 염라대왕
	EFFECT_DIE_HELLKING						,
	EFFECT_SELECT_HELLKING					,	// 800

	EFFECT_ATTACK_GHOSTSAMURAI				,	// 유령사무라이
	EFFECT_DIE_GHOSTSAMURAI					,
	EFFECT_SELECT_GHOSTSAMURAI				,
	EFFECT_ATTACK_PYTHON					,	// 이무기
	EFFECT_DIE_PYTHON						,
	EFFECT_SELECT_PYTHON					,
	EFFECT_ATTACK_HELLMESSENGER				,	// 저승사자
	EFFECT_DIE_HELLMESSENGER				,
	EFFECT_SELECT_HELLMESSENGER				,
	EFFECT_ATTACK_JINEMPEROR				,	// 810 진시황의혼

	EFFECT_DIE_JINEMPEROR					,
	EFFECT_SELECT_JINEMPEROR				,
	EFFECT_GUARDIAN_MOUSE_RECALL			,	// 수호부[쥐]
	EFFECT_GUARDIAN_MOUSE_ATTACK			,
	EFFECT_GUARDIAN_MOUSE_DIE				,
	EFFECT_GUARDIAN_CAW_RECALL				,	// 수호부[소]
	EFFECT_GUARDIAN_CAW_RECALL2				,
	EFFECT_GUARDIAN_CAW_ATTACK1				,
	EFFECT_GUARDIAN_CAW_ATTACK2				,
	EFFECT_GUARDIAN_CAW_ATTACK3				,	// 820

	EFFECT_GUARDIAN_CAW_DIE1				,
	EFFECT_GUARDIAN_CAW_DIE2				,
	EFFECT_GUARDIAN_CAW_DIE3				,
	EFFECT_GUARDIAN_TIGER_ATTACK			,	// 수호부[호랑이]
	EFFECT_GUARDIAN_TIGER_END				,
	EFFECT_GUARDIAN_DRAGON_ATTACK			,	// 수호부[용]
	EFFECT_GUARDIAN_HORSE_ATTACK			,	// 수호부[말]
	EFFECT_GUARDIAN_HORSE_END				,
	EFFECT_GUARDIAN_RABBIT_ATTACK			,	// 수호부[토끼]
	EFFECT_GUARDIAN_RABBIT_END				,	// 830

	EFFECT_GUARDIAN_SNAKE_RECALL			,
	EFFECT_GUARDIAN_SHEEP_ATTACK			,
	EFFECT_GUARDIAN_MONKEY_RECALL			,
	EFFECT_GUARDIAN_MONKEY_ATTACK			,
	EFFECT_GUARDIAN_MONKEY_DIE				,
	EFFECT_GUARDIAN_CHICK_RECALL			,
	EFFECT_GUARDIAN_CHICK_ATTACK			,
	EFFECT_GUARDIAN_CHICK_DIE				,
	EFFECT_GUARDIAN_DOG_ATTACK				,
	EFFECT_GUARDIAN_PIG_RECALL				,// 840

	EFFECT_GUARDIAN_PIG_ATTACK				,
	EFFECT_GUARDIAN_PIG_DIE					,

	EFFECT_SMALLGANG_C						,
	EFFECT_HOSPITAL_C						,
	EFFECT_DIE_HOSPITAL_C					,
	EFFECT_TEAM1_C							,
	EFFECT_TEAM2_C							,
	EFFECT_TEAM3_C							,
	EFFECT_TEAM4_C							,
	EFFECT_TEAM5_C							,// 850
	EFFECT_TEAM6_C							,
	EFFECT_TEAM7_C							,
	EFFECT_TEAM8_C							,
	EFFECT_TEAM9_C							,
	EFFECT_TEAM10_C							,
	EFFECT_MBARRACK_C						,
	EFFECT_BARRACK_C						,
	EFFECT_NOT_HOSPITAL_C					,
	EFFECT_FOOD_VEGETABLE					,
	EFFECT_FOOD_TEA							,//860
	EFFECT_FOOD_SPECIAL						,
	EFFECT_FOOD_NUDDLE						,
	EFFECT_FOOD_MEAT						,
	EFFECT_FOOD_FRUITS						,
	EFFECT_FOOD_ETC							,

	// robypark 2004/6/22 17:21
	// 2차 장수 공격관련 효과음
	EFFECT_FIRE_KU102AE1					, // 거북차 무기 발사 효과음
	EFFECT_EXP_KU102AE2						, // 거북차 총알 폭발 효과음
	EFFECT_FIRE_KU103AE2					, // 뇌전차 번개 발사 효과음
	EFFECT_FIRE_JU104AE1					, // 지진차 발사 효과음
	EFFECT_EXP_JU104AE2						, // 870 // 지진차 지진 효과음
	EFFECT_FIRE_JU105AE1					, // 흑룡차 발사 효과음
	EFFECT_EXP_JU105AE2						, // 흑룡차 폭발 효과음
	EFFECT_FIRE_CU106AE1					, // 발석거 발사 효과음
	EFFECT_EXP_CU106AE2						, // 발석거 총알 폭발 효과음
	EFFECT_FIRE_CU107AE1					, // 불랑기포차 발사 효과음
	EFFECT_EXP_CU107AE2						, // 불랑기포차 총알 폭발 효과음
	EFFECT_FIRE_TU108AE1					, // 화룡차 창 공격 효과음
	EFFECT_FIRE_TU108AE2					, // 화룡차 총알 발사 효과음
	EFFECT_EXP_TU108AE3						, // 화룡차 총알 폭발 효과음
	EFFECT_FIRE_TU109AE1					, // 880 // 봉황비조 발사 효과음
	EFFECT_EXP_TU109AE2						, // 봉황비조 총알 폭발 효과음

	// robypark 2004/12/17 15:56 공성전 효과음 추가										
	// 칼 소리,		쨍쨍 거리는 칼등이 서로 부딫히는 소리
	EFFECT_BLADEATTACK						,
	// 활 쏘는 소리		활을 쏘는 소리	
	EFFECT_BOWATTACK						,
	// 발석거 돌 쏠때 소리		발석거가 돌을 쏠 때 소리
	EFFECT_CATAPULTATTACK					,
	//충차 공격 소리		충차가(성벽을 부수는 기계) 공격 하는 소리
	EFFECT_WALLBREAKERATTACK				,
	// 칼 맞을 때		칼에 맞았을 떄 베이는 소리
	EFFECT_BLADEHIT							,
	// 활 맞을 떄		활을 맞았을 때 화살이 박히는 소리
	EFFECT_BOWHIT							,
	// 발석거에게 맞을 때		발석거의 돌에 맞았을 때 소리
	EFFECT_CATAPULTHIT						,
	// 충차에게 맞을 때	창칼 맞을 때와 같은 그림이나 소리는 다르게 나야함.(충차 그림에 함꼐 표시됨)	성벽이 충차에게 두들겨 맞을 때 소리
	EFFECT_WALLBREAKERHIT					,
	// 창 공격 소리
	EFFECT_SPEARATTACK						,	// 890
	// 창 공격에 맞는 소리
	EFFECT_SPEARHIT							,
	// 방어력 향상 소리	그림 제작중	성벽의 방어력을 향상하는 소리
	EFFECT_WALLREPAIR						,
	// 인간 부대 이동시		검병, 창병, 궁병의 부대가 이동할 때 내는 기합소리
	EFFECT_ARMYMOVE							,
	// 기마병 부대 이동시		기마병 부대가 이동할 때 나는 말 발굽 소리
	EFFECT_CAVALRYMOVE						,
	// 발석거 이동시		발석거가 이동할 때 나는 묵직한 기계음 소리
	EFFECT_CATAPULTMOVE						,
	// 충차 이동시		충차가 이동할 때 나는 묵직한 기계음 소리
	EFFECT_WALLBREAKERMOVE					,
	// 공성 유니트 변신 소리		유저가 공성 유니트로 변신 할 때 나는 소리
	EFFECT_UNITCHANGE						,
	// 공성 유니트 전멸 시	위와 상동	모든 공성 유니트는 죽는 것이 아니라 다시 유저의 모습으로 돌아가므로 변신시와 동일하게 적절한 마법적 효과음이 필요
	EFFECT_UNITDEAD							,
	// 병력 충원시	그림 제작중	소모된 부대를 충원할 떄 나는 소리
	EFFECT_SUPPLEMENT						,
	// 치명적 공격		크리티컬 공격이 발동했을 때 나는 소리
	EFFECT_CRITICAL							,	// 900
	// 견고한 방어		견고한 방어가 발동했을 떄 나는 소리
	EFFECT_DEFENCE							,

	MAX_EFFECT_TYPE								// 총 이펙트 수
};

#define SOUNDNUM_PER_EFFECT			5
#define MAX_EFFECT_BUFFER			10	// 5

class _EffectData 
{
public:
	char	m_pszString[48];						// Effect Kind
	SHORT	EffectNumber;							// 해당 Effect의 Sound 개수
	SHORT	EffectID[SOUNDNUM_PER_EFFECT];			// 불러와진 효과음의 아이디 값을 저장한다.
	DWORD	EffectPlayClock[SOUNDNUM_PER_EFFECT];

	void	Free();
	BOOL	Play(SI32 x, SI32 y);
};

class _EffectBuffer 
{
public:
	SHORT Effect;
	SHORT X, Y;
	
	void Set(SHORT effect, SHORT x, SHORT y)	{ Effect = effect; X = x; Y = y; };
};


//-----------------------------------------------------------------------------
// Name: EffectMgr
// Code: damduk
// Desc: SoundEffect 데이터를 관리하는 클래스이다.
//-----------------------------------------------------------------------------
class EffectDataMgr : public CSingleton<EffectDataMgr>
{
private:
	_EffectData		m_EffectData[MAX_EFFECT_TYPE];		// 모든 사운드 데이타

public:
	_EffectBuffer	m_EffectBuffer[MAX_EFFECT_BUFFER];	// 플레이 되어야할 사운드 큐버퍼
	SHORT			m_EffectBufferIndex;

private:
	void	Init();
	void	Free();
	/// 2004-08-18 15:32 sagolboss 추가 : 파서에서 읽어왔을때 혹시 빈칸(스페이스)가 들어있다면 고쳐준다.
	BOOL	ClearBlankString(char const* pszCheckString, char* pszOutCleanBlankString); 

#ifndef _USE_HASHCODE_EFFECTSOUND
	void	SetEnumType( int index, char *pszStr );		// Define된 Effect의 Type을 설정한다.
	void	SetProtocol();
#endif

public:
#ifndef _USE_HASHCODE_EFFECTSOUND
	ENUM_EFFECT_TYPE	GetEnumType		( char *pszStr ); //원래 코드 (sagolboss)
#else
	int					GetEnumType		( char *pszStr );
#endif
	const char*			GetEnumType		( int  enIndex );
	int					GetMaxCount	( void )	{ return MAX_EFFECT_TYPE; }

	void	Pop();

	void	PushEffectByKindWhenSelected(SI32 kind);	// kind에 의한 선택시 효과음 연주

	EffectDataMgr();
	~EffectDataMgr();

#ifdef _USE_HASHCODE_EFFECTSOUND
/** 수정자 : 김성준 (sagolboss)
	날  짜 : 2004-08-16 14:14 
	설  명 : CMyHashTable 클래스 추가 */
private:
	CMyHashTable<int>* m_pMyHashTable;
public:
	inline CMyHashTable<int>* GetMyHashTable() { return m_pMyHashTable; }
#endif 
};

#ifdef _USE_HASHCODE_EFFECTSOUND
#define PushEffect(EffectName, x, y) HashCodePushEffect(#EffectName, x, y)
BOOL	HashCodePushEffect(const char* pszEffectName, SHORT x, SHORT y);
BOOL	HashCodePushEffect(int nEffectIndex, SHORT x, SHORT y);
#else
BOOL	PushEffect(SHORT effect, SHORT x, SHORT y);		// EffectDataMgr 내부함수로 들어가야하지만 수백개의 에러들... ㅠㅠ
#endif

inline EffectDataMgr *GetEffectDataMgr()
{
	return (EffectDataMgr *)EffectDataMgr::GetManagePtr();
}
#endif