#ifndef IMJIN2_RESULTMANAGEMENT_SPR_HEADER
#define	IMJIN2_RESULTMANAGEMENT_SPR_HEADER

#define	Y_RESULT_SPR_FILE_NUM							4
#define	Y_RESULT_0_SPR_FILENAME							"yfnt\\resultspr_01.spr"
#define	Y_RESULT_1_SPR_FILENAME							"yfnt\\resultspr_02.spr"
#define	Y_RESULT_2_SPR_FILENAME							"yfnt\\resultspr_03.spr"
#define	Y_RESULT_3_SPR_FILENAME							"yfnt\\resultspr_04.spr"

#define	Y_RESULT_BAR_FILENAME							"yfnt\\resultbar.spr"

#define	Y_RESULT_TOTAL_FILENUMBER						0
#define	Y_RESULT_CHARACTER_FILENUMBER					1
#define	Y_RESULT_STRUCTURE_FILENUMBER					2
#define	Y_RESULT_RESOURCE_FILENUMBER					3

#define	Y_RESULT_FONTNUM_TOTAL_ONMOUSE					0
#define	Y_RESULT_FONTNUM_CHARACTER_ONMOUSE				1
#define	Y_RESULT_FONTNUM_STRUCTURE_ONMOUSE				2
#define	Y_RESULT_FONTNUM_RESOURCE_ONMOUSE				3

#define	Y_RESULT_TOTAL_X								138
#define	Y_RESULT_TOTAL_Y								61
#define	Y_RESULT_TOTAL_WIDTH							88
#define	Y_RESULT_TOTAL_HEIGHT							28


#define	Y_RESULT_CHARACTER_X							230
#define	Y_RESULT_CHARACTER_Y							Y_RESULT_TOTAL_Y
#define	Y_RESULT_CHARACTER_WIDTH						Y_RESULT_TOTAL_WIDTH
#define	Y_RESULT_CHARACTER_HEIGHT						Y_RESULT_TOTAL_HEIGHT

#define	Y_RESULT_STRUCTURE_X							320
#define	Y_RESULT_STRUCTURE_Y							Y_RESULT_TOTAL_Y
#define	Y_RESULT_STRUCTURE_WIDTH						Y_RESULT_TOTAL_WIDTH
#define	Y_RESULT_STRUCTURE_HEIGHT						Y_RESULT_TOTAL_HEIGHT

#define	Y_RESULT_RESOURCE_X								414
#define	Y_RESULT_RESOURCE_Y								Y_RESULT_TOTAL_Y
#define	Y_RESULT_RESOURCE_WIDTH							Y_RESULT_TOTAL_WIDTH
#define	Y_RESULT_RESOURCE_HEIGHT						Y_RESULT_TOTAL_HEIGHT

// 임진록 2 PLUS에 관한 부분...
#ifdef _IMJIN2PLUS

#undef	Y_RESULT_TOTAL_X
#undef	Y_RESULT_TOTAL_Y
#undef	Y_RESULT_TOTAL_WIDTH
#undef	Y_RESULT_TOTAL_HEIGHT

#undef	Y_RESULT_CHARACTER_X
#undef	Y_RESULT_CHARACTER_Y
#undef	Y_RESULT_CHARACTER_WIDTH
#undef	Y_RESULT_CHARACTER_HEIGHT

#undef	Y_RESULT_STRUCTURE_X
#undef	Y_RESULT_STRUCTURE_Y
#undef	Y_RESULT_STRUCTURE_WIDTH
#undef	Y_RESULT_STRUCTURE_HEIGHT

#undef	Y_RESULT_RESOURCE_X
#undef	Y_RESULT_RESOURCE_Y
#undef	Y_RESULT_RESOURCE_WIDTH
#undef	Y_RESULT_RESOURCE_HEIGHT
				

#define	Y_RESULT_TOTAL_X								64
#define	Y_RESULT_TOTAL_Y								65
#define	Y_RESULT_TOTAL_WIDTH							140
#define	Y_RESULT_TOTAL_HEIGHT							29


#define	Y_RESULT_CHARACTER_X							237
#define	Y_RESULT_CHARACTER_Y							65
#define	Y_RESULT_CHARACTER_WIDTH						140
#define	Y_RESULT_CHARACTER_HEIGHT						29

#define	Y_RESULT_STRUCTURE_X							410
#define	Y_RESULT_STRUCTURE_Y							65
#define	Y_RESULT_STRUCTURE_WIDTH						140
#define	Y_RESULT_STRUCTURE_HEIGHT						29

#define	Y_RESULT_RESOURCE_X								584
#define	Y_RESULT_RESOURCE_Y								65
#define	Y_RESULT_RESOURCE_WIDTH							140
#define	Y_RESULT_RESOURCE_HEIGHT						20
#endif


#endif

